#+title: "C-c C-v t"
#+property: header-args:emacs-lisp :tangle ~/.emacs.d/init.el

Personal GNU Emacs configuration!

* Global keybindings

|-----+------------------------+---------------------|
| Key | Control                | Meta                |
|-----+------------------------+---------------------|
| Q   |                        |                     |
| W   | kill-region            | kill-ring-save      |
| E   | move-end-of-line       |                     |
| R   | [[Expand-region][er/expand-region]]       |                     |
| T   | transpose-chars        | transpose-words     |
| Y   | yank                   | yank-pop            |
| U   |                        | upcase-word         |
| I   |                        |                     |
| O   | open-line              |                     |
| P   | previous-line          |                     |
|-----+------------------------+---------------------|
| A   | move-beginning-of-line |                     |
| S   | isearch-forward        |                     |
| D   | delete-char            |                     |
| F   | forward-char           | forward-word        |
| G   | keyboard-quit          |                     |
| H   | C-h                    |                     |
| J   |                        |                     |
| K   | kill-line              |                     |
| L   | recenter-top-bottom    | downcase-word       |
|-----+------------------------+---------------------|
| Z   |                        |                     |
| X   | C-x                    | M-x                 |
| C   | C-c                    | capitalize-word     |
| V   | scroll-up-command      | scroll-down-command |
| B   | backward-char          | backward-word       |
| N   | next-line              |                     |
| M   | newline                |                     |
|-----+------------------------+---------------------|

* Essentials

The most general and basic part of the configuration that either prepares background for the other pieces, or simply has no better place to be.

** Package management

Downloading, configuring and using packages.

*** Straight

[[https://github.com/raxod502/straight.el][Straight]] package manager. Making =*straight-process*= invisible.

#+begin_src emacs-lisp
(setq straight-process-buffer " *straight-process*")

(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))
#+end_src

*** Use-package

Integration with [[https://github.com/jwiegley/use-package][use-package]].

#+begin_src emacs-lisp
(straight-use-package 'use-package)
(setq straight-use-package-by-default t)
#+end_src

** No-littering

Using [[https://github.com/emacscollective/no-littering][no-littering]] package to help keeping =~/.emacs.d/= clean.

#+begin_src emacs-lisp
(use-package no-littering
  :custom
  (auto-save-file-name-transforms `((".*" ,(no-littering-expand-var-file-name "auto-save/") t)))
  (custom-file (no-littering-expand-etc-file-name "custom.el")))
#+end_src

* Expand-region

Expanding region using [[https://github.com/magnars/expand-region.el][expand-region]].

#+begin_src emacs-lisp
(use-package expand-region
  :bind ("C-r" . er/expand-region)
  :config (setq expand-region-fast-keys-enabled nil))
#+end_src
