#+title: "C-c C-v t"
#+property: header-args:emacs-lisp :tangle ~/.emacs.d/init.el

* Basic configuration

** Package management

*** Straight

[[https://github.com/raxod502/straight.el][Straight]] package manager.

#+begin_src emacs-lisp
(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

(setq package-enable-at-startup nil)
#+end_src

*** Use-package

Integration with [[https://github.com/jwiegley/use-package][use-package]].

#+begin_src emacs-lisp
(straight-use-package 'use-package)
(setq straight-use-package-by-default t)
#+end_src

** Files location

Using [[https://github.com/emacscollective/no-littering][no-littering]] package to help keeping =~/.emacs.d/= clean.

#+begin_src emacs-lisp
(use-package no-littering
  :custom
  (auto-save-file-name-transforms `((".*" ,(no-littering-expand-var-file-name "auto-save/") t)))
  (custom-file (no-littering-expand-etc-file-name "custom.el")))
#+end_src

* Face

** General UI configuration

Omitting the welcome page, disabling useless parts of UI and setting the distance between sides and text.

#+begin_src emacs-lisp
(setq inhibit-startup-message t)

(scroll-bar-mode -1)
(tool-bar-mode -1)
(tooltip-mode -1)
(menu-bar-mode -1)

(set-fringe-mode 5)
#+end_src

** Theme

[[https://draculatheme.com/emacs][Dracula]] theme.

#+begin_src emacs-lisp
(use-package dracula-theme)
(load-theme 'dracula t)
#+end_src

** Font

Setting [[https://github.com/tonsky/FiraCode][Fira Code]] (without ligatures) font with a proper size. Downloaded from =ttf-fira-code= Arch Linux package.

#+begin_src emacs-lisp
(set-face-attribute 'default nil
                    :font "Fira Code"
                    :height 115)
#+end_src

** Indentation

No tabs allowed!

#+begin_src emacs-lisp
(setq-default indent-tabs-mode nil)
#+end_src

** Delimiters

[[https://github.com/Fanael/rainbow-delimiters][Rainbow delimiters]] for all programming modes with 3 levels and custom colors.

#+begin_src emacs-lisp
(use-package rainbow-delimiters
  :hook (prog-mode . rainbow-delimiters-mode)
  :custom (rainbow-delimiters-max-face-count 3))

(custom-set-faces
 '(rainbow-delimiters-depth-1-face ((t (:foreground "#ee9999"))))
 '(rainbow-delimiters-depth-2-face ((t (:foreground "#99ee99"))))
 '(rainbow-delimiters-depth-3-face ((t (:foreground "#9999ee")))))
#+end_src

* Minibuffer

** Searching

Searching with [[https://github.com/abo-abo/swiper#swiper][swiper]].

#+begin_src emacs-lisp
(use-package swiper
  :bind (("C-s" . swiper)))
#+end_src

** Completion

*** Functions

Selecting with tab when only one option remains.

#+begin_src emacs-lisp
(defun minibuffer-select-by-tab ()
  (interactive)
  (if (or (and (not (string= (substring (vertico--candidate) -1) "/"))
               (and (car vertico--candidates)
                    (not (cdr vertico--candidates))))
          (string= (thing-at-point 'sexp t) (vertico--candidate)))
      (vertico-exit)
    (vertico-insert)))
#+end_src

Going one level up by pressing backscape in minibuffer find file.

#+begin_src emacs-lisp
(defun minibuffer-kill-directory-name (arg)
  (interactive "p")
  (if minibuffer-completing-file-name
      (if (string-match-p "/." (minibuffer-contents))
          (zap-up-to-char (- arg) ?/)
        (delete-minibuffer-contents))
    (delete-backward-char arg)))
#+end_src

No kill-ring insertion in minibuffer.

#+begin_src emacs-lisp
(add-hook 'minibuffer-setup-hook
          (lambda ()
            (make-local-variable 'kill-ring)))
#+end_src

*** Packages

Completion by [[https://github.com/minad/vertico][vertico]] and [[https://github.com/oantolin/orderless][orderless]], additional info from [[https://github.com/minad/marginalia][marginalia]].

#+begin_src emacs-lisp
(use-package vertico
  :init
  (vertico-mode)
  (savehist-mode)
  :bind (:map minibuffer-local-map
         ("<tab>" . minibuffer-select-by-tab)
         ("<DEL>" . minibuffer-kill-directory-name)))

(use-package orderless
  :custom (completion-styles '(orderless)))

(use-package marginalia
  :init (marginalia-mode))
#+end_src

** Advice

[[https://github.com/justbur/emacs-which-key][Which-key]] and [[https://github.com/Wilfred/helpful][helpful]] to seek wisdom.

#+begin_src emacs-lisp
(use-package which-key
  :init (which-key-mode)
  :config (setq which-key-idle-delay 1))

(use-package helpful
  :bind (("C-h f"   . helpful-callable)
         ("C-h k"   . helpful-key)
         ("C-h v"   . helpful-variable)
         ("C-h C-h" . helpful-at-point)))
#+end_src

* Major modes

** Magit

Git client [[https://magit.vc/][magit]].

#+begin_src emacs-lisp
(use-package magit
  :config (setq magit-section-visibility-indicator nil))
#+end_src

** Org mode

*** Basics

Updating [[https://orgmode.org/][org mode]], setting the indentation and color.

#+begin_src emacs-lisp
(use-package org
  :config
  (setq org-src-preserve-indentation 1)
  (setq org-startup-indented 1)
  (set-face-background 'org-block "#2e303c"))
#+end_src

*** Org tempo

Shortcuts for code blocks.

#+begin_src emacs-lisp
(with-eval-after-load 'org
  (require 'org-tempo)

  (add-to-list 'org-structure-template-alist '("co" . "src conf"))
  (add-to-list 'org-structure-template-alist '("el" . "src emacs-lisp"))
  (add-to-list 'org-structure-template-alist '("hs" . "src haskell"))
  (add-to-list 'org-structure-template-alist '("sh" . "src shell")))
#+end_src

* Programming languages

** Haskell

[[https://github.com/haskell/haskell-mode][Haskell mode]].

#+begin_src emacs-lisp
(use-package haskell-mode)
#+end_src
