#+title: "C-c C-v t"
#+property: header-args:emacs-lisp :tangle ~/.emacs.d/init.el

Personal GNU Emacs configuration!

* Essentials

The most general and basic part of the configuration that either prepares background for the other pieces, or simply has no better place to be.

** Package management

Downloading, configuring and using packages.

*** Straight

[[https://github.com/raxod502/straight.el][Straight]] package manager. Making =*straight-process*= invisible.

#+begin_src emacs-lisp
(setq straight-process-buffer " *straight-process*")

(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))
#+end_src

*** Use-package

Integration with [[https://github.com/jwiegley/use-package][use-package]].

#+begin_src emacs-lisp
(straight-use-package 'use-package)
(setq straight-use-package-by-default t)
#+end_src

** No-littering

Using [[https://github.com/emacscollective/no-littering][no-littering]] package to help keeping =~/.emacs.d/= clean.

#+begin_src emacs-lisp
(use-package no-littering
  :config
  (setq auto-save-file-name-transforms `((".*" ,(no-littering-expand-var-file-name "auto-save/") t)))
  (setq custom-file (no-littering-expand-etc-file-name "custom.el")))
#+end_src

** Indentation

Tabs disabled globally.

#+begin_src emacs-lisp
(setq-default indent-tabs-mode nil)
#+end_src

* Editing text

Customizing the customizable editor.

** Movement

|---------------------+---------|
| Name                | Binding |
|---------------------+---------|
| scroll-up-command   | C-v     |
| scroll-down-command | M-v     |
| recenter-top-bottom | C-l     |
| forward-char        | C-f     |
| backward-char       | C-b     |
| forward-word        | M-f     |
| backward-word       | M-b     |
| avy-goto-char       | C-j     |
|---------------------+---------|

*** Avy

Jumping to characters with [[https://github.com/abo-abo/avy][avy]].

#+begin_src emacs-lisp
(use-package avy
  :bind* ("C-j" . avy-goto-char))
#+end_src

** Lines

|------------------------+---------|
| Name                   | Binding |
|------------------------+---------|
| move-beginning-of-line | C-a     |
| move-end-of-line       | C-e     |
| next-line              | C-n     |
| previous-line          | C-p     |
| open-line              | C-o     |
| newline                | C-m     |
| kill-line              | C-k     |
|------------------------+---------|

** Mark

|------------------+---------|
| Name             | Binding |
|------------------+---------|
| set-mark-command | C-SPC   |
| kill-region      | C-w     |
| kill-ring-save   | M-w     |
| yank             | C-y     |
| yank-pop         | M-y     |
| expand-region    | C-r     |
|------------------+---------|

*** Expand-region

Expanding region using [[https://github.com/magnars/expand-region.el][expand-region]]. Marked text is replaced by typing.

#+begin_src emacs-lisp
(use-package expand-region
  :bind ("C-r" . er/expand-region)
  :config
  (setq expand-region-fast-keys-enabled nil)
  (delete-selection-mode 1))
#+end_src

** Swapping

|-----------------+---------|
| Name            | Binding |
|-----------------+---------|
| transpose-chars | C-t     |
| transpose-words | M-t     |
| downcase-word   | M-l     |
| upcase-word     | M-u     |
| capitalize-word | M-c     |
|-----------------+---------|

* Face

** General UI configuration

Omitting the welcome page, disabling mouse related parts of UI and setting the distance between sides and text.

#+begin_src emacs-lisp
(setq inhibit-startup-message t)

(scroll-bar-mode -1)
(tool-bar-mode -1)
(tooltip-mode -1)
(menu-bar-mode -1)

(set-fringe-mode 5)
#+end_src

** Theme

[[https://draculatheme.com/emacs][Dracula]] theme.

#+begin_src emacs-lisp
(use-package dracula-theme
  :config (load-theme 'dracula t))
#+end_src

** Font

Setting [[https://github.com/tonsky/FiraCode][Fira Code]] (without ligatures) font with a proper size.

#+begin_src emacs-lisp
(set-face-attribute 'default nil
                    :font "Fira Code"
                    :height 115)
#+end_src

** Mode-line

Custom mode-line.

#+begin_src emacs-lisp
(defface sb/mode-line-not-saved
  '((t :foreground "orange"
       :weight bold))
  "Face for tilde before file name.")

(setq-default mode-line-format
              '("%e "
                (:eval (if (and (buffer-file-name)
                                (buffer-modified-p))
                           (propertize "~" 'face 'sb/mode-line-not-saved)
                         " "))
                (:eval (propertize "%b" 'face 'bold))
                "   %p L%l    %m"))
#+end_src

** Delimiters

[[https://github.com/Fanael/rainbow-delimiters][Rainbow delimiters]] for all programming modes with 3 levels and custom colors. White indicates errors.

#+begin_src emacs-lisp
(use-package rainbow-delimiters
  :hook (prog-mode . rainbow-delimiters-mode)
  :config (setq rainbow-delimiters-max-face-count 3))

(custom-set-faces
 '(rainbow-delimiters-depth-1-face ((t (:foreground "#ee9999"))))
 '(rainbow-delimiters-depth-2-face ((t (:foreground "#99ee99"))))
 '(rainbow-delimiters-depth-3-face ((t (:foreground "#9999ee"))))

 '(rainbow-delimiters-mismatched-face ((t (:foreground "#ffffff"))))
 '(rainbow-delimiters-unmatched-face ((t (:foreground "#ffffff")))))
#+end_src
