#+title: "C-c C-v t"
#+property: header-args :mkdirp yes
#+property: header-args:emacs-lisp :tangle ~/.emacs.d/init.el

Personal GNU Emacs configuration!

* Contents                                                              :TOC:
- [[#essentials][Essentials]]
  - [[#package-management][Package management]]
  - [[#no-littering][No-littering]]
  - [[#indentation][Indentation]]
  - [[#advice][Advice]]
  - [[#save-place-mode][Save-place-mode]]
  - [[#magit][Magit]]
  - [[#ansi-term][Ansi-term]]
- [[#editing-text][Editing text]]
  - [[#free-keys][Free keys]]
  - [[#movement][Movement]]
  - [[#lines][Lines]]
  - [[#region][Region]]
  - [[#swapping][Swapping]]
  - [[#others][Others]]
- [[#face][Face]]
  - [[#general-ui-configuration][General UI configuration]]
  - [[#theme][Theme]]
  - [[#font][Font]]
  - [[#mode-line][Mode-line]]
  - [[#minibuffer][Minibuffer]]
  - [[#delimiters][Delimiters]]
  - [[#highlight-numbers][Highlight numbers]]
  - [[#modified-faces][Modified faces]]
- [[#org-mode][Org mode]]
  - [[#markup][Markup]]
  - [[#links][Links]]
  - [[#task-management][Task management]]
  - [[#indentation-1][Indentation]]
  - [[#org-tempo][Org tempo]]
  - [[#table-of-contents][Table of contents]]
- [[#programming-modes][Programming modes]]
  - [[#haskell][Haskell]]
  - [[#python][Python]]
- [[#window-manager][Window manager]]

* Essentials

The most general and basic part of the configuration that either prepares background for the other pieces, or simply has no better place to be.

** Package management

Downloading, configuring and using packages.

*** Straight

[[https://github.com/raxod502/straight.el][Straight]] package manager. Making =*straight-process*= invisible.

#+begin_src emacs-lisp
(setq straight-process-buffer " *straight-process*")

(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))
#+end_src

*** Use-package

Integration with [[https://github.com/jwiegley/use-package][use-package]].

#+begin_src emacs-lisp
(straight-use-package 'use-package)
(setq straight-use-package-by-default t)
#+end_src

** No-littering

Using [[https://github.com/emacscollective/no-littering][no-littering]] package to help keeping =~/.emacs.d/= clean.

#+begin_src emacs-lisp
(use-package no-littering
  :config
  (setq auto-save-file-name-transforms `((".*" ,(no-littering-expand-var-file-name "auto-save/") t)))
  (setq custom-file (no-littering-expand-etc-file-name "custom.el")))
#+end_src

** Indentation

Tabs disabled globally.

#+begin_src emacs-lisp
(setq-default indent-tabs-mode nil)
#+end_src

** Advice

[[https://github.com/justbur/emacs-which-key][Which-key]] and [[https://github.com/Wilfred/helpful][helpful]] to seek wisdom.

#+begin_src emacs-lisp
(use-package which-key
  :init (which-key-mode)
  :config (setq which-key-idle-delay 1))

(use-package helpful
  :bind (("C-h f"   . helpful-callable)
         ("C-h k"   . helpful-key)
         ("C-h v"   . helpful-variable)
         ("C-h C-h" . helpful-at-point)))
#+end_src

** Save-place-mode

Saving the cursor position in file associated buffers.

#+begin_src emacs-lisp
(save-place-mode 1)
#+end_src

** Magit

Git client [[https://github.com/magit/magit][Magit]].

#+begin_src emacs-lisp
(use-package magit
  :config (setq magit-section-visibility-indicator nil))
#+end_src

** Ansi-term

A terminal emulator. =C-c C-j= switches to =line sub-mode= in which it's possible to use common editing commands. =C-c C-k= to get back.

#+begin_src emacs-lisp
(defun sb/ansi-term-bash ()
  (interactive)
  (ansi-term "/bin/bash"))

(bind-key "C-x x t" 'sb/ansi-term-bash)

(define-advice term-handle-exit
    (:after (process-name msg))
  (kill-buffer (current-buffer)))
#+end_src

* Editing text

Customizing the customizable editor.

** Free keys

The keys that are by default globally bound to commands not used by me.

*** Control

=i=, =o=, =j=.

*** Meta

=e=, =i=, =o=, =p=, =s=, =d=, =g=, =h=, =j=, =k=, =z=, =n=.

** Movement

The basic commands to move in buffers.

|--------------------------------+---------|
| Name                           | Binding |
|--------------------------------+---------|
| scroll-up-command              | C-v     |
| scroll-down-command            | M-v     |
| recenter-top-bottom            | C-l     |
| move-to-window-line-top-bottom | M-r     |
| forward-char                   | C-f     |
| backward-char                  | C-b     |
| forward-word                   | M-f     |
| backward-word                  | M-b     |
| isearch-forward                | C-s     |
|--------------------------------+---------|

** Lines

Line-oriented functions.

|------------------------+---------|
| Name                   | Binding |
|------------------------+---------|
| move-beginning-of-line | C-a     |
| back-to-indentation    | M-m     |
| move-end-of-line       | C-e     |
| next-line              | C-n     |
| previous-line          | C-p     |
| newline                | C-m     |
| delete-char            | C-d     |
| kill-line              | C-k     |
| fill-paragraph         | M-q     |
| delete-backward-char   | DEL     |
| delete-indentation     | C-DEL   |
|------------------------+---------|

*** Deleting indentation

Moving to previous line with =C-backspace=.

#+begin_src emacs-lisp
(bind-key* "<C-backspace>" 'delete-indentation)
#+end_src

** Region

Setting the mark and selecting text.

|------------------------+---------|
| Name                   | Binding |
|------------------------+---------|
| set-mark-command       | C-SPC   |
| kill-region            | C-w     |
| kill-ring-save         | M-w     |
| yank                   | C-y     |
| yank-pop               | M-y     |
| expand-region          | C-r     |
| mc/mark-all-like-this  | C-<     |
| mc/mark-next-like-this | C->     |
|------------------------+---------|

*** Expand-region

Expanding region using [[https://github.com/magnars/expand-region.el][expand-region]]. Marked text is replaced by typing.

#+begin_src emacs-lisp
(use-package expand-region
  :bind ("C-r" . er/expand-region)
  :config
  (setq expand-region-fast-keys-enabled nil)
  (delete-selection-mode 1))
#+end_src

*** Multiple-cursors

Having [[https://github.com/magnars/multiple-cursors.el][multiple-cursors]] in emacs. Enter key works as expected.

#+begin_src emacs-lisp
(use-package multiple-cursors
  :bind (("C-<" . mc/mark-all-like-this)
         ("C->" . mc/mark-next-like-this)))

(add-hook 'multiple-cursors-mode-hook
          (lambda ()
            (unbind-key "<return>" mc/keymap)))
#+end_src

** Swapping

Changing the order or capitalization.

|-----------------+---------|
| Name            | Binding |
|-----------------+---------|
| transpose-chars | C-t     |
| transpose-words | M-t     |
| downcase-word   | M-l     |
| upcase-word     | M-u     |
| capitalize-word | M-c     |
|-----------------+---------|

** Others

|--------------------------+---------|
| Name                     | Binding |
|--------------------------+---------|
| keyboard-quit            | C-g     |
| universal-argument       | C-u     |
| fill-paragraph           | C-q     |
| suspend-frame            | C-z     |
| execute-extended-command | M-x     |
| help prefix              | C-h     |
| general prefix           | C-x     |
| mode specific prefix     | C-c     |
|--------------------------+---------|

* Face

Setting how it all looks.

** General UI configuration

Omitting the welcome page, disabling mouse related parts of UI and setting the distance between sides and text.

#+begin_src emacs-lisp
(setq inhibit-startup-message t)

(scroll-bar-mode -1)
(tool-bar-mode -1)
(tooltip-mode -1)
(menu-bar-mode -1)

(set-fringe-mode 5)
#+end_src

** Theme

[[https://github.com/dracula/emacs][Dracula]] theme. Slightly modifified.

#+begin_src emacs-lisp
(use-package dracula-theme
  :config (load-theme 'dracula t))
#+end_src

** Font

Setting [[https://github.com/tonsky/FiraCode][Fira Code]] (without ligatures) font with a proper size.

#+begin_src emacs-lisp
(when (x-list-fonts "Fira Code")
  (set-face-attribute 'default nil
                      :font "Fira Code"
                      :height 115))
#+end_src

** Mode-line

Custom mode-line.

#+begin_src emacs-lisp
(defface sb/mode-line-not-saved
  '((t :foreground "orange"
       :weight bold))
  "Face for tilde before file name.")

(setq-default mode-line-format
              '("%e "
                (:eval (if (and (buffer-file-name)
                                (buffer-modified-p))
                           (propertize "~" 'face 'sb/mode-line-not-saved)
                         " "))
                (:eval (unless (buffer-file-name)
                         "  "))
                (:eval (propertize "%b" 'face 'bold))
                (:eval (when (buffer-file-name)
                         "   %p L%l    %m"))))
#+end_src

*** Uniquify

Shows directories before file names in mode-line in case of multiple buffers with identical file names.

#+begin_src emacs-lisp
(require 'uniquify)
(setq uniquify-buffer-name-style 'forward)
#+end_src

** Minibuffer

Going one directory up by pressing backscape in minibuffer find file. Jumps directly to =/= from =~/=.

#+begin_src emacs-lisp
(defun sb/minibuffer-kill-directory-name (arg)
  "One directory up in find file minibuffer."
  (interactive "p")
  (if minibuffer-completing-file-name
      (unless (string= (minibuffer-contents) "/")
        (if (string= (minibuffer-contents) "~/")
            (progn
              (delete-minibuffer-contents)
              (self-insert-command 1 47))
          (if (string= (substring (minibuffer-contents) -1) "/")
              (zap-up-to-char (- arg) ?/)
            (delete-backward-char arg))))
    (delete-backward-char arg)))
#+end_src

No kill-ring insertion in minibuffer.

#+begin_src emacs-lisp
(add-hook 'minibuffer-setup-hook
          (lambda ()
            (make-local-variable 'kill-ring)))
#+end_src

Completion by [[https://github.com/minad/vertico][vertico]], additional info from [[https://github.com/minad/marginalia][marginalia]].

#+begin_src emacs-lisp
(when (> emacs-major-version 26)
  (use-package vertico
    :init
    (vertico-mode)
    (savehist-mode)
    :bind (:map minibuffer-local-map
           ("<DEL>" . sb/minibuffer-kill-directory-name)))

  (use-package marginalia
    :init (marginalia-mode)))
#+end_src

[[https://github.com/oantolin/orderless][Orderless]] completion style.

#+begin_src emacs-lisp
(use-package orderless
  :config (setq completion-styles '(orderless)))
#+end_src

** Delimiters

[[https://github.com/Fanael/rainbow-delimiters][Rainbow delimiters]] for all programming modes.

#+begin_src emacs-lisp
(use-package rainbow-delimiters
  :hook (prog-mode . rainbow-delimiters-mode)
  :config (setq rainbow-delimiters-max-face-count 3))
#+end_src

** Highlight numbers

Making numbers yellow.

#+begin_src emacs-lisp
(use-package highlight-numbers
  :hook (prog-mode . highlight-numbers-mode))
#+end_src

** Modified faces

A low budget version of creating my own theme.

*** Weight

Making more faces =semi-bold=.

#+begin_src emacs-lisp
(dolist (face '(bold
                font-lock-keyword-face
                font-lock-variable-name-face
                font-lock-function-name-face
                font-lock-type-face))
  (set-face-attribute face nil :weight 'semi-bold))
#+end_src

*** Font lock

=Yellow= and =blue= will join the default =pink= for syntax highlighting.

#+begin_src emacs-lisp
(dolist (face '(font-lock-builtin-face
                font-lock-constant-face
                font-lock-string-face))
  (set-face-foreground face "#f5dd0a"))

(dolist (face '(font-lock-function-name-face
                font-lock-type-face))
  (set-face-foreground face "#0adef5"))
#+end_src

*** Rainbow delimiters

Three levels and custom colors. White indicates errors.

#+begin_src emacs-lisp
(with-eval-after-load 'rainbow-delimiters
  (set-face-foreground 'rainbow-delimiters-depth-1-face "#e69191")
  (set-face-foreground 'rainbow-delimiters-depth-2-face "#91e6a3")
  (set-face-foreground 'rainbow-delimiters-depth-3-face "#b691e6")

  (dolist (face '(rainbow-delimiters-mismatched-face
                  rainbow-delimiters-unmatched-face))
    (set-face-foreground face "#ffffff")
    (set-face-attribute face nil :weight 'semi-bold)))
#+end_src

*** Marginalia

File privilege colors. Orange and green respectively.

#+begin_src emacs-lisp
(with-eval-after-load 'marginalia
  (set-face-foreground 'marginalia-file-priv-write "#ffb86c")
  (set-face-attribute 'marginalia-file-priv-write nil :weight 'semi-bold)
  (set-face-foreground 'marginalia-file-priv-exec "#50fa7b"))
#+end_src

*** Org code blocks

White text, slightly lighter background. Orange heading level 1 and grey =this=.

#+begin_src emacs-lisp
(with-eval-after-load 'org
  (set-face-foreground 'org-block "#ffffff")
  (set-face-background 'org-block "#2e303c")
  (set-face-foreground 'org-level-1 "#ffb86c")
  (set-face-foreground 'org-verbatim "#6272a4"))
#+end_src

* Org mode

The [[https://orgmode.org/][mode to organize everything]].

** Markup

Structuring and highlighting text.

|----------------------+-------------------|
| Construct            | Notation          |
|----------------------+-------------------|
| big heading          | one asterisk      |
| small heading        | two asterisks     |
| even smaller heading | three asterisks   |
| *bold*               | asterisks around  |
| =verbatim=           | equal sign around |
| +crossed+            | plus sign around  |
|----------------------+-------------------|

Show the hidden part of document when attempted to modify it.

#+begin_src emacs-lisp
(setq org-catch-invisible-edits t)
#+end_src

Showing and hiding with =TAB= and =S-TAB=.

** Links

Inserting links after setting the region.

|---------------+-----------------------------------------|
| Link          | Action                                  |
|---------------+-----------------------------------------|
| web page link | C-c C-l =url=                           |
| file link     | in file =org-store-link= in org C-c C-l |
| open link     | C-c C-o or mouse click                  |
|---------------+-----------------------------------------|

** Task management

TODO cycle with =C-c C-t=, org agenda bound to =M-a=.

*** Agenda

Files and keybindings for the [[https://orgmode.org/manual/Agenda-Views.html#Agenda-Views][agenda]].

#+begin_src emacs-lisp
(bind-key* "M-a" 'org-agenda)
(setq org-agenda-files '("~/muni/Tasks.org"))
#+end_src

*** Calendar

Week begins on Monday.

#+begin_src emacs-lisp
(setq calendar-week-start-day 1)
#+end_src

** Indentation

Automatically indented and with visual lines.

#+begin_src emacs-lisp
(setq org-startup-indented 1)
(setq org-src-preserve-indentation 1)

(add-hook 'org-mode-hook
          'visual-line-mode)
#+end_src

** Org tempo

Shortcuts for code block languages.

#+begin_src emacs-lisp
(when (> emacs-major-version 26)
  (with-eval-after-load 'org
    (require 'org-tempo)
    (dolist (language '(("co" . "src conf")
                        ("el" . "src emacs-lisp")
                        ("hs" . "src haskell")
                        ("sh" . "src shell")
                        ("tx" . "src text")))
      (add-to-list 'org-structure-template-alist language))))
#+end_src

** Table of contents

Automatic table of contents [[https://github.com/snosov1/toc-org][generator]]. =TOC= attribute should be on heading.

#+begin_src emacs-lisp
(use-package toc-org
  :hook (org-mode . toc-org-mode))
#+end_src

* Programming modes

|--------------------------+---------|
| Name                     | Binding |
|--------------------------+---------|
| launch REPL process      | C-c C-p |
| current buffer into REPL | C-c C-c |
| clear REPL               | C-l     |
| move to previous line    | M-^     |
|--------------------------+---------|

** Haskell

The official [[https://github.com/haskell/haskell-mode][Haskell-mode]].

#+begin_src emacs-lisp
(use-package haskell-mode
  :bind (:map haskell-mode-map
         ("C-c C-p" . haskell-process-reload)
         ("C-c C-c" . haskell-process-load-file))
  :config
  (setq haskell-indentation-starter-offset 4)
  (setq haskell-indentation-left-offset 4)
  (setq haskell-indentation-layout-offset 4)
  (setq haskell-indentation-where-pre-offset 4)
  (setq haskell-indentation-where-post-offset 4)
  (setq haskell-interactive-popup-errors nil))
#+end_src

*** Interactive mode

=C-l= clear.

#+begin_src emacs-lisp
(with-eval-after-load 'haskell-interactive-mode
  (bind-key "C-l" 'haskell-interactive-mode-clear 'haskell-interactive-mode-map))
#+end_src

** Python

Python-mode - the one already included in emacs.

*** Indentation

Do not guess anything, Python should be indented with 4 spaces.

#+begin_src emacs-lisp
(setq python-indent-guess-indent-offset nil)
#+end_src

*** Interactive process

Clear the REPL buffer by =C-l=.

#+begin_src emacs-lisp
(bind-key "C-l" 'comint-clear-buffer 'comint-mode-map)
#+end_src

*** Modules

Flake8 and mypy.

#+begin_src emacs-lisp
(defun sb/python-execute-flake8 ()
  (interactive)
  (python-shell-send-string (concat
                             "subprocess.run(["
                             "\"flake8\", "
                             "\"" buffer-file-name "\"])")))

(defun sb/python-execute-mypy ()
  (interactive)
  (python-shell-send-string (concat "subprocess.run(["
                                    "\"mypy\", "
                                    "\"--strict\", "
                                    "\"" buffer-file-name "\"])")))

(with-eval-after-load 'python
  (add-hook 'inferior-python-mode-hook
            (lambda ()
              (python-shell-send-string "import subprocess")))
  (bind-key "C-c f" 'sb/python-execute-flake8 'python-mode-map)
  (bind-key "C-c m" 'sb/python-execute-mypy 'python-mode-map))
#+end_src

*** Typing

Add typing imports automatically.

#+begin_src emacs-lisp
(defun sb/python-update-typing-imports ()
  (interactive)
  (save-excursion
    (goto-char (point-min))
    (when (re-search-forward "^from typing" nil t)
      (move-beginning-of-line 1)
      (kill-line)
      (kill-line))
    (goto-char (point-min))
    (let ((types ""))
      (dolist (type '("Dict" "List" "Optional" "Set" "Tuple"))
        (when (save-excursion
                (search-forward type nil t))
          (setf types (concat types type ", "))))
      (when (not (string= types ""))
        (insert (concat "from typing import "
                        (substring types 0 -2)))
        (newline)))))

(with-eval-after-load 'python
  (bind-key "C-c i" 'sb/python-update-typing-imports 'python-mode-map))
#+end_src

* Window manager

[[https://github.com/ch11ng/exwm][Emacs X Window Manager]]. Gets executed if its configuration file exists.

#+begin_src emacs-lisp
(when (file-exists-p (concat user-emacs-directory
                             "lisp/window-manager.el"))
  (add-to-list 'load-path "~/.emacs.d/lisp/")
  (require 'window-manager))
#+end_src
