#+title: "C-c C-v t"
#+property: header-args:emacs-lisp :tangle ~/.emacs.d/init.el

Personal GNU Emacs configuration!

* Essentials

The most general and basic part of the configuration that either prepares background for the other pieces, or simply has no better place to be.

** Package management

Downloading, configuring and using packages.

*** Straight

[[https://github.com/raxod502/straight.el][Straight]] package manager. Making =*straight-process*= invisible.

#+begin_src emacs-lisp
(setq straight-process-buffer " *straight-process*")

(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))
#+end_src

*** Use-package

Integration with [[https://github.com/jwiegley/use-package][use-package]].

#+begin_src emacs-lisp
(straight-use-package 'use-package)
(setq straight-use-package-by-default t)
#+end_src

** No-littering

Using [[https://github.com/emacscollective/no-littering][no-littering]] package to help keeping =~/.emacs.d/= clean.

#+begin_src emacs-lisp
(use-package no-littering
  :config
  (setq auto-save-file-name-transforms `((".*" ,(no-littering-expand-var-file-name "auto-save/") t)))
  (setq custom-file (no-littering-expand-etc-file-name "custom.el")))
#+end_src

** Indentation

Tabs disabled globally.

#+begin_src emacs-lisp
(setq-default indent-tabs-mode nil)
#+end_src

** Advice

[[https://github.com/justbur/emacs-which-key][Which-key]] and [[https://github.com/Wilfred/helpful][helpful]] to seek wisdom.

#+begin_src emacs-lisp
(use-package which-key
  :init (which-key-mode)
  :config (setq which-key-idle-delay 1))

(use-package helpful
  :bind (("C-h f"   . helpful-callable)
         ("C-h k"   . helpful-key)
         ("C-h v"   . helpful-variable)
         ("C-h C-h" . helpful-at-point)))
#+end_src

** Save-place-mode

Saving the cursor position in file associated buffers.

#+begin_src emacs-lisp
(save-place-mode 1)
#+end_src

* Editing text

Customizing the customizable editor.

** Movement

|---------------------+---------|
| Name                | Binding |
|---------------------+---------|
| scroll-up-command   | C-v     |
| scroll-down-command | M-v     |
| recenter-top-bottom | C-l     |
| forward-char        | C-f     |
| backward-char       | C-b     |
| forward-word        | M-f     |
| backward-word       | M-b     |
| avy-goto-char       | C-j     |
| consult-line        | C-s     |
|---------------------+---------|

*** Avy

Jumping to characters with [[https://github.com/abo-abo/avy][avy]].

#+begin_src emacs-lisp
(use-package avy
  :bind* ("C-j" . avy-goto-char))
#+end_src

*** Consult-line

Searching in current file with [[https://github.com/minad/consult][consult]].

#+begin_src emacs-lisp
(use-package consult
  :bind (("C-s" . consult-line)))
#+end_src

** Lines

|------------------------+---------|
| Name                   | Binding |
|------------------------+---------|
| move-beginning-of-line | C-a     |
| back-to-indentation    | M-m     |
| move-end-of-line       | C-e     |
| next-line              | C-n     |
| previous-line          | C-p     |
| open-line              | C-o     |
| newline                | C-m     |
| kill-line              | C-k     |
|------------------------+---------|

** Region

|------------------------+---------|
| Name                   | Binding |
|------------------------+---------|
| set-mark-command       | C-SPC   |
| kill-region            | C-w     |
| kill-ring-save         | M-w     |
| yank                   | C-y     |
| yank-pop               | M-y     |
| expand-region          | C-r     |
| mc/mark-all-like-this  | C-<     |
| mc/mark-next-like-this | C->     |
|------------------------+---------|

*** Expand-region

Expanding region using [[https://github.com/magnars/expand-region.el][expand-region]]. Marked text is replaced by typing.

#+begin_src emacs-lisp
(use-package expand-region
  :bind ("C-r" . er/expand-region)
  :config
  (setq expand-region-fast-keys-enabled nil)
  (delete-selection-mode 1))
#+end_src

*** Multiple-cursors

Having [[https://github.com/magnars/multiple-cursors.el][multiple-cursors]] in emacs. Enter key works as expected.

#+begin_src emacs-lisp
(use-package multiple-cursors
  :bind (("C-<" . mc/mark-all-like-this)
         ("C->" . mc/mark-next-like-this)))

(add-hook 'multiple-cursors-mode-hook
          (lambda ()
            (unbind-key "<return>" mc/keymap)))
#+end_src

** Swapping

|-----------------+---------|
| Name            | Binding |
|-----------------+---------|
| transpose-chars | C-t     |
| transpose-words | M-t     |
| downcase-word   | M-l     |
| upcase-word     | M-u     |
| capitalize-word | M-c     |
|-----------------+---------|

* Face

Setting how it all looks.

** General UI configuration

Omitting the welcome page, disabling mouse related parts of UI and setting the distance between sides and text.

#+begin_src emacs-lisp
(setq inhibit-startup-message t)

(scroll-bar-mode -1)
(tool-bar-mode -1)
(tooltip-mode -1)
(menu-bar-mode -1)

(set-fringe-mode 5)
#+end_src

** Theme

[[https://github.com/dracula/emacs][Dracula]] theme.

#+begin_src emacs-lisp
(use-package dracula-theme
  :config (load-theme 'dracula t))
#+end_src

** Font

Setting [[https://github.com/tonsky/FiraCode][Fira Code]] (without ligatures) font with a proper size.

#+begin_src emacs-lisp
(set-face-attribute 'default nil
                    :font "Fira Code"
                    :height 115)
#+end_src

** Mode-line

Custom mode-line.

#+begin_src emacs-lisp
(defface sb/mode-line-not-saved
  '((t :foreground "orange"
       :weight bold))
  "Face for tilde before file name.")

(setq-default mode-line-format
              '("%e "
                (:eval (if (and (buffer-file-name)
                                (buffer-modified-p))
                           (propertize "~" 'face 'sb/mode-line-not-saved)
                         " "))
                (:eval (propertize "%b" 'face 'bold))
                "   %p L%l    %m"))
#+end_src

*** Uniquify

Shows directories before file names in mode-line in case of multiple buffers with identical file names.

#+begin_src emacs-lisp
(require 'uniquify)
(setq uniquify-buffer-name-style 'forward)
#+end_src

** Minibuffer

Going one directory up by pressing backscape in minibuffer find file. Jumps directly to =/= from =~/=.

#+begin_src emacs-lisp
(defun sb/minibuffer-kill-directory-name (arg)
  (interactive "p")
  (if minibuffer-completing-file-name
      (unless (string= (minibuffer-contents) "/")
        (if (string= (minibuffer-contents) "~/")
            (progn
              (delete-minibuffer-contents)
              (self-insert-command 1 47))
          (if (string= (substring (minibuffer-contents) -1) "/")
              (zap-up-to-char (- arg) ?/)
            (delete-backward-char arg))))
    (delete-backward-char arg)))
#+end_src

No kill-ring insertion in minibuffer.

#+begin_src emacs-lisp
(add-hook 'minibuffer-setup-hook
          (lambda ()
            (make-local-variable 'kill-ring)))
#+end_src

Completion by [[https://github.com/minad/vertico][vertico]] and [[https://github.com/oantolin/orderless][orderless]], additional info from [[https://github.com/minad/marginalia][marginalia]].

#+begin_src emacs-lisp
(use-package vertico
  :init
  (vertico-mode)
  (savehist-mode)
  :bind (:map minibuffer-local-map
         ("<DEL>" . sb/minibuffer-kill-directory-name)))

(use-package orderless
  :config (setq completion-styles '(orderless)))

(use-package marginalia
  :init (marginalia-mode))
#+end_src

** Delimiters

[[https://github.com/Fanael/rainbow-delimiters][Rainbow delimiters]] for all programming modes.

#+begin_src emacs-lisp
(use-package rainbow-delimiters
  :hook (prog-mode . rainbow-delimiters-mode)
  :config (setq rainbow-delimiters-max-face-count 3))
#+end_src

** Modified faces

When the defaults weren't too appealing...

*** Weight

Making more faces =semi-bold=.

#+begin_src emacs-lisp
(dolist (face '(bold
                font-lock-keyword-face
                font-lock-variable-name-face
                font-lock-function-name-face
                font-lock-type-face))
  (set-face-attribute face nil :weight 'semi-bold))
#+end_src

*** Rainbow delimiters colors

Three levels and custom colors. White indicates errors.

#+begin_src emacs-lisp
(custom-set-faces
 '(rainbow-delimiters-depth-1-face ((t (:foreground "#ee9999"))))
 '(rainbow-delimiters-depth-2-face ((t (:foreground "#99ee99"))))
 '(rainbow-delimiters-depth-3-face ((t (:foreground "#9999ee"))))

 '(rainbow-delimiters-mismatched-face ((t (:foreground "#ffffff"
                                           :weight bold))))
 '(rainbow-delimiters-unmatched-face ((t (:foreground "#ffffff"
                                          :weight bold)))))
#+end_src

*** Org mode code blocks

White text, slightly lighter background.

#+begin_src emacs-lisp
(with-eval-after-load 'org
  (set-face-foreground 'org-block "#ffffff")
  (set-face-background 'org-block "#2e303c"))
#+end_src

* Major modes

The big packages unassociated with a single programming language.

** Magit

Git client [[https://github.com/magit/magit][Magit]].

#+begin_src emacs-lisp
(use-package magit
  :config (setq magit-section-visibility-indicator nil))
#+end_src

** Org mode

Org mode.

*** Indentation

Automatically indented and with visual lines.

#+begin_src emacs-lisp
(setq org-startup-indented 1)
(setq org-src-preserve-indentation 1)

(add-hook 'org-mode-hook
          'visual-line-mode)
#+end_src

*** Org tempo

Shortcuts for code block languages.

#+begin_src emacs-lisp
(with-eval-after-load 'org
  (require 'org-tempo)
  (dolist (language '(("co" . "src conf")
                      ("el" . "src emacs-lisp")
                      ("hs" . "src haskell")
                      ("sh" . "src shell")
                      ("tx" . "src text")))
    (add-to-list 'org-structure-template-alist language)))
#+end_src

** Vterm

Terminal emulator [[https://github.com/akermu/emacs-libvterm][Vterm]].

#+begin_src emacs-lisp
(use-package vterm
  :bind ("C-$" . vterm-other-window))
#+end_src

* Programming languages

** Haskell

The official [[https://github.com/haskell/haskell-mode][Haskell-mode]].

#+begin_src emacs-lisp
(use-package haskell-mode)
#+end_src

** Python

Python-mode - the one already included in emacs.

*** Indentation

Do not guess anything, Python should be indented with 4 spaces.

#+begin_src emacs-lisp
(setq python-indent-guess-indent-offset nil)
#+end_src

* Snippets

** YASnippet

The [[https://github.com/joaotavora/yasnippet][template system]] for Emacs.

#+begin_src emacs-lisp
(use-package yasnippet
  :config
  (setq yas-indent-line 'fixed)
  (yas-global-mode 1))
#+end_src

** Org Mode

*** New snippet

#+begin_src snippet :tangle ~/.emacs.d/etc/yasnippet/snippets/org-mode/newsnippet :mkdirp yes
# -*- mode: snippet -*-
# name: newsnippet
# key: n
# --
`"#+begin_src"` snippet :tangle ~/.emacs.d/etc/yasnippet/snippets/${1:mode}/${2:name} :mkdirp yes
# -*- mode: snippet -*-
`"#"` name: $2
`"#"` key: ${3:key}
# --
$0
`"#+end_src"`
#+end_src

** Python mode

*** Print

#+begin_src snippet :tangle ~/.emacs.d/etc/yasnippet/snippets/python-mode/print :mkdirp yes
# -*- mode: snippet -*-
# name: print
# key: p
# --
print("well done!")
#+end_src
