#+title: "C-c C-v t"
#+property: header-args :mkdirp yes
#+property: header-args:emacs-lisp :tangle ~/.emacs.d/init.el

Personal GNU Emacs configuration.

* Contents                                                              :TOC:

- [[#essentials][Essentials]]
  - [[#package-management][Package management]]
  - [[#no-littering][No-littering]]
- [[#editing-text][Editing text]]
  - [[#free-keys][Free keys]]
  - [[#movement][Movement]]
  - [[#lines][Lines]]
  - [[#region][Region]]
  - [[#swapping][Swapping]]
  - [[#others][Others]]
- [[#face][Face]]
  - [[#general-ui-configuration][General UI configuration]]
  - [[#theme][Theme]]
  - [[#font][Font]]
  - [[#mode-line][Mode-line]]
  - [[#minibuffer][Minibuffer]]
  - [[#advice][Advice]]
  - [[#modified-faces][Modified faces]]
- [[#big-packages][Big packages]]
  - [[#org-mode][Org mode]]
  - [[#magit][Magit]]
  - [[#ansi-term][Ansi-term]]
- [[#programming-modes][Programming modes]]
  - [[#general][General]]
  - [[#c][C]]
  - [[#haskell][Haskell]]
  - [[#python][Python]]
- [[#snippets][Snippets]]
  - [[#tables][Tables]]
  - [[#org-mode-1][Org mode]]
- [[#window-manager][Window manager]]

* Essentials

Part of the configuration that prepares background for all the other pieces.

** Package management

Downloading, configuring and using packages.

*** Straight

[[https://github.com/raxod502/straight.el][Straight]] package manager. Making =*straight-process*= invisible.

#+begin_src emacs-lisp
(setq straight-process-buffer " *straight-process*")

(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))
#+end_src

*** Use-package

Integration with [[https://github.com/jwiegley/use-package][use-package]].

#+begin_src emacs-lisp
(straight-use-package 'use-package)
(setq straight-use-package-by-default t)
#+end_src

** No-littering

Using [[https://github.com/emacscollective/no-littering][no-littering]] package to help keeping =~/.emacs.d/= clean.

#+begin_src emacs-lisp
(use-package no-littering
  :config
  (setq auto-save-file-name-transforms `((".*" ,(no-littering-expand-var-file-name "auto-save/") t)))
  (setq custom-file (no-littering-expand-etc-file-name "custom.el")))
#+end_src

* Editing text

Customizing the customizable editor.

** Free keys

The keys that are by default globally bound to commands not used by me.

*** Control

=i=, =o=.

*** Meta

=e=, =i=, =o=, =p=, =s=, =d=, =g=, =h=, =j=, =k=, =z=, =n=.

** Movement

The basic commands to move in buffers.

|--------------------------------+---------|
| Name                           | Binding |
|--------------------------------+---------|
| scroll-up-command              | C-v     |
| scroll-down-command            | M-v     |
| recenter-top-bottom            | C-l     |
| move-to-window-line-top-bottom | M-r     |
| forward-char                   | C-f     |
| backward-char                  | C-b     |
| forward-word                   | M-f     |
| backward-word                  | M-b     |
| consult-line                   | C-s     |
|--------------------------------+---------|

Searching in current file with [[https://github.com/minad/consult][consult]].

#+begin_src emacs-lisp
(when (> emacs-major-version 26)
  (use-package consult
    :bind (("C-s" . consult-line))))
#+end_src

** Lines

Line-oriented functions.

|------------------------+---------|
| Name                   | Binding |
|------------------------+---------|
| move-beginning-of-line | C-a     |
| back-to-indentation    | M-m     |
| move-end-of-line       | C-e     |
| next-line              | C-n     |
| previous-line          | C-p     |
| newline                | C-m     |
| delete-char            | C-d     |
| kill-line              | C-k     |
| fill-paragraph         | M-q     |
| delete-backward-char   | DEL     |
| delete-indentation     | C-j     |
|------------------------+---------|

*** Deleting indentation

Remove indentation and move to the previous line with what's after the point.

#+begin_src emacs-lisp
(bind-key* "C-j" 'delete-indentation)
#+end_src

** Region

Setting the mark and selecting text.

|------------------------+---------|
| Name                   | Binding |
|------------------------+---------|
| set-mark-command       | C-SPC   |
| kill-region            | C-w     |
| kill-ring-save         | M-w     |
| yank                   | C-y     |
| yank-pop               | M-y     |
| expand-region          | C-r     |
| mc/mark-all-like-this  | C-<     |
| mc/mark-next-like-this | C->     |
|------------------------+---------|

*** Expand-region

Expanding region using [[https://github.com/magnars/expand-region.el][expand-region]]. Marked text is replaced by typing.

#+begin_src emacs-lisp
(use-package expand-region
  :bind ("C-r" . er/expand-region)
  :config
  (setq expand-region-fast-keys-enabled nil)
  (delete-selection-mode 1))
#+end_src

*** Multiple-cursors

Having [[https://github.com/magnars/multiple-cursors.el][multiple-cursors]] in emacs. Enter key works as expected.

#+begin_src emacs-lisp
(use-package multiple-cursors
  :bind (("C-<" . mc/mark-all-like-this)
         ("C->" . mc/mark-next-like-this)))

(add-hook 'multiple-cursors-mode-hook
          (lambda ()
            (unbind-key "<return>" mc/keymap)))
#+end_src

** Swapping

Changing the order or capitalization.

|-----------------+---------|
| Name            | Binding |
|-----------------+---------|
| transpose-chars | C-t     |
| transpose-words | M-t     |
| downcase-word   | M-l     |
| upcase-word     | M-u     |
| capitalize-word | M-c     |
|-----------------+---------|

** Others

|--------------------------+---------|
| Name                     | Binding |
|--------------------------+---------|
| keyboard-quit            | C-g     |
| universal-argument       | C-u     |
| fill-paragraph           | C-q     |
| suspend-frame            | C-z     |
| execute-extended-command | M-x     |
| help prefix              | C-h     |
| general prefix           | C-x     |
| mode specific prefix     | C-c     |
|--------------------------+---------|

* Face

Setting how it all looks.

** General UI configuration

Omitting the welcome page, disabling mouse related parts of UI and setting the distance between sides and text.

#+begin_src emacs-lisp
(setq inhibit-startup-message t)

(scroll-bar-mode -1)
(tool-bar-mode -1)
(tooltip-mode -1)
(menu-bar-mode -1)

(set-fringe-mode 5)
#+end_src

** Theme

[[https://github.com/dracula/emacs][Dracula]] theme. Slightly modifified.

#+begin_src emacs-lisp
(use-package dracula-theme
  :config (load-theme 'dracula t))
#+end_src

** Font

Setting [[https://github.com/tonsky/FiraCode][Fira Code]] (without ligatures) font with a proper size.

#+begin_src emacs-lisp
(when (x-list-fonts "Fira Code")
  (set-face-attribute 'default nil
                      :font "Fira Code"
                      :height 115))
#+end_src

** Mode-line

Custom mode-line.

#+begin_src emacs-lisp
(defface sb/mode-line-not-saved
  '((t :foreground "orange"
       :weight bold))
  "Face for tilde before file name.")

(setq-default mode-line-format
              '("%e "
                (:eval (if (and (buffer-file-name)
                                (buffer-modified-p))
                           (propertize "~" 'face 'sb/mode-line-not-saved)
                         " "))
                (:eval (unless (buffer-file-name)
                         "  "))
                (:eval (propertize "%b" 'face 'bold))
                (:eval (when (buffer-file-name)
                         "   %p L%l    %m"))))
#+end_src

*** Uniquify

Shows directories before file names in mode-line in case of multiple buffers with identical file names.

#+begin_src emacs-lisp
(require 'uniquify)
(setq uniquify-buffer-name-style 'forward)
#+end_src

** Minibuffer

Going one directory up by pressing backspace in minibuffer find file. Jumps directly to =/= from =~/=.

#+begin_src emacs-lisp
(defun sb/minibuffer-kill-directory-name (arg)
  "One directory up in find file minibuffer."
  (interactive "p")
  (if minibuffer-completing-file-name
      (unless (string= (minibuffer-contents) "/")
        (if (string= (minibuffer-contents) "~/")
            (progn
              (delete-minibuffer-contents)
              (self-insert-command 1 47))
          (if (string= (substring (minibuffer-contents) -1) "/")
              (zap-up-to-char (- arg) ?/)
            (delete-backward-char arg))))
    (delete-backward-char arg)))
#+end_src

No kill-ring insertion in minibuffer.

#+begin_src emacs-lisp
(add-hook 'minibuffer-setup-hook
          (lambda ()
            (make-local-variable 'kill-ring)))
#+end_src

Completion by [[https://github.com/minad/vertico][vertico]], additional info from [[https://github.com/minad/marginalia][marginalia]].

#+begin_src emacs-lisp
(when (> emacs-major-version 26)
  (use-package vertico
    :init
    (vertico-mode)
    (savehist-mode)
    :bind (:map minibuffer-local-map
           ("<DEL>" . sb/minibuffer-kill-directory-name)))

  (use-package marginalia
    :init (marginalia-mode)))
#+end_src

[[https://github.com/oantolin/orderless][Orderless]] completion style.

#+begin_src emacs-lisp
(use-package orderless
  :config (setq completion-styles '(orderless)))
#+end_src

** Advice

Improving emacs’ self-documenting capabilities with [[https://github.com/justbur/emacs-which-key][which-key]] and [[https://github.com/Wilfred/helpful][helpful]].

#+begin_src emacs-lisp
(use-package which-key
  :init (which-key-mode)
  :config (setq which-key-idle-delay 1))

(use-package helpful
  :bind (("C-h f"   . helpful-callable)
         ("C-h k"   . helpful-key)
         ("C-h v"   . helpful-variable)
         ("C-h C-h" . helpful-at-point)))
#+end_src

** Modified faces

A low budget version of creating my own theme.

*** Weight

Making more faces =semi-bold=.

#+begin_src emacs-lisp
(dolist (face '(bold
                font-lock-keyword-face
                font-lock-variable-name-face
                font-lock-function-name-face
                font-lock-type-face))
  (set-face-attribute face nil :weight 'semi-bold))
#+end_src

*** Font lock

=Yellow= and =blue= will join the default =pink= for syntax highlighting.

#+begin_src emacs-lisp
(dolist (face '(font-lock-builtin-face
                font-lock-constant-face
                font-lock-string-face))
  (set-face-foreground face "#f5dd0a"))

(dolist (face '(font-lock-function-name-face
                font-lock-type-face))
  (set-face-foreground face "#0adef5"))
#+end_src

*** Rainbow delimiters

Three levels and custom colors. White indicates errors.

#+begin_src emacs-lisp
(with-eval-after-load 'rainbow-delimiters
  (set-face-foreground 'rainbow-delimiters-depth-1-face "#e69191")
  (set-face-foreground 'rainbow-delimiters-depth-2-face "#91e6a3")
  (set-face-foreground 'rainbow-delimiters-depth-3-face "#b691e6")

  (dolist (face '(rainbow-delimiters-mismatched-face
                  rainbow-delimiters-unmatched-face))
    (set-face-foreground face "#ffffff")
    (set-face-attribute face nil :weight 'semi-bold)))
#+end_src

*** Marginalia

File privilege colors. Orange and green respectively.

#+begin_src emacs-lisp
(with-eval-after-load 'marginalia
  (set-face-foreground 'marginalia-file-priv-write "#ffb86c")
  (set-face-attribute 'marginalia-file-priv-write nil :weight 'semi-bold)
  (set-face-foreground 'marginalia-file-priv-exec "#50fa7b"))
#+end_src

*** Org code blocks

White text, slightly lighter background. Orange heading level 1, purple links and grey =this=.

#+begin_src emacs-lisp
(with-eval-after-load 'org
  (set-face-foreground 'org-block "#ffffff")
  (set-face-background 'org-block "#2e303c")
  (set-face-foreground 'org-level-1 "#ffb86c")
  (set-face-foreground 'org-link "#bd93f9")
  (set-face-foreground 'org-verbatim "#6272a4"))
#+end_src

*** Which key

Purple links in which-key buffers.

#+begin_src emacs-lisp
(with-eval-after-load 'which-key
  (set-face-foreground 'button "#bd93f9"))
#+end_src

*** Magit

Purple links in magit buffers.

#+begin_src emacs-lisp
(with-eval-after-load 'magit
  (set-face-foreground 'link "#bd93f9"))
#+end_src

* Big packages

Those that have functionality way beyond text editing.

** Org mode

The [[https://orgmode.org/][best mode for writing config files]].

*** Markup

Structuring and highlighting text.

|----------------------+-------------------|
| Construct            | Notation          |
|----------------------+-------------------|
| big heading          | one asterisk      |
| small heading        | two asterisks     |
| even smaller heading | three asterisks   |
| *bold*               | asterisks around  |
| =verbatim=           | equal sign around |
| +crossed+            | plus sign around  |
|----------------------+-------------------|

Show the hidden part of document when attempted to modify it.

#+begin_src emacs-lisp
(setq org-catch-invisible-edits t)
#+end_src

Showing and hiding with =TAB= and =S-TAB=.

*** Links

Inserting links after setting the region.

|---------------+-----------------------------------------|
| Link          | Action                                  |
|---------------+-----------------------------------------|
| web page link | C-c C-l =url=                           |
| file link     | C-c C-l =file=, =file-path=             |
| open link     | C-c C-o or mouse click                  |
|---------------+-----------------------------------------|

*** Indentation

Automatically indented and with visual lines.

#+begin_src emacs-lisp
(setq org-startup-indented 1)
(setq org-src-preserve-indentation 1)

(add-hook 'org-mode-hook
          'visual-line-mode)
#+end_src

*** Table of contents

Automatic table of contents [[https://github.com/snosov1/toc-org][generator]]. =TOC= attribute should be on heading.

#+begin_src emacs-lisp
(use-package toc-org
  :hook (org-mode . toc-org-mode))

(define-advice toc-org-insert-toc
    (:after (&optional dry-run))
  (save-excursion
    (goto-char (point-min))
    (when (re-search-forward ":TOC:" nil t)
      (next-line)
      (beginning-of-line)
      (unless (char-equal (char-after) ?\n)
        (org-return)))))
#+end_src

** Magit

Git client [[https://github.com/magit/magit][Magit]].

#+begin_src emacs-lisp
(use-package magit
  :config (setq magit-section-visibility-indicator nil))
#+end_src

** Ansi-term

A terminal emulator. =C-c C-j= switches to =line sub-mode= in which it's possible to use common editing commands. =C-c C-k= to get back.

#+begin_src emacs-lisp
(defun sb/ansi-term-bash ()
  (interactive)
  (ansi-term "/bin/bash"))

(bind-key "C-x x t" 'sb/ansi-term-bash)

(define-advice term-handle-exit
    (:after (process-name msg))
  (kill-buffer (current-buffer)))
#+end_src

* Programming modes

|--------------------------+---------|
| Name                     | Binding |
|--------------------------+---------|
| launch REPL process      | C-c C-p |
| current buffer into REPL | C-c C-c |
| clear REPL               | C-l     |
|--------------------------+---------|

** General

*** Indentation

Not using tabs by default.

#+begin_src emacs-lisp
(setq-default indent-tabs-mode nil)
#+end_src

*** Highlight numbers

Making [[https://github.com/Fanael/highlight-numbers][numbers]] yellow.

#+begin_src emacs-lisp
(use-package highlight-numbers
  :hook (prog-mode . highlight-numbers-mode))
#+end_src

*** Delimiters

[[https://github.com/Fanael/rainbow-delimiters][Rainbow delimiters]] for all programming modes.

#+begin_src emacs-lisp
(use-package rainbow-delimiters
  :hook (prog-mode . rainbow-delimiters-mode)
  :config (setq rainbow-delimiters-max-face-count 3))
#+end_src

*** Pair completion

Inserting closing delimiters and quotation marks automatically after typing the opening ones. The latter is apparently meant to be used for [[https://www.gnu.org/software/emacs/manual/html_node/emacs/Quotation-Marks.html][something else]] (to type curved quotes), so the third line is there to avoid doing exactly that in org mode. Pair will surround region if mark is active.

#+begin_src emacs-lisp
(electric-pair-mode)
(electric-quote-mode)
(setq electric-quote-chars nil)
#+end_src

*** Semicolons

Add [[https://github.com/iquiw/smart-semicolon][semicolon]] to the end of a line. If it is already there, insert semicolon at point.

#+begin_src emacs-lisp
(use-package smart-semicolon)

(dolist (hook '(c-mode-hook java-mode-hook))
  (add-hook hook 'smart-semicolon-mode))
#+end_src

*** Save-place-mode

Remember the cursor position in file associated buffers.

#+begin_src emacs-lisp
(save-place-mode 1)
#+end_src

*** Flycheck

[[https://www.flycheck.org/en/latest/][Syntax checker]]. =C-c f= the prefix key, errors will not be shown while typing.

#+begin_src emacs-lisp
(use-package flycheck
  :config
  (setq flycheck-indication-mode nil)
  (setq flycheck-check-syntax-automatically '(mode-enabled save)))

(define-key flycheck-mode-map flycheck-keymap-prefix nil)
(setq flycheck-keymap-prefix (kbd "C-c f"))
(define-key flycheck-mode-map flycheck-keymap-prefix
  flycheck-command-map)
#+end_src

** C

Mode for C files.

*** Style

K&R with 4 space indentation.

#+begin_src emacs-lisp
(with-eval-after-load 'cc-mode
  (setq c-basic-offset 4)
  (push '(other . "k&r") c-default-style))
#+end_src

*** Syntax

Gcc before cppcheck. Not using =-Werror= because it would just repaint orange with red.

#+begin_src emacs-lisp
(add-hook 'c-mode-hook 'flycheck-mode)

(setq-default flycheck-disabled-checkers '(c/c++-clang))

(setq flycheck-gcc-language-standard "c99")
(setq flycheck-gcc-args '("-pedantic"
                          "-Wall"
                          "-Wextra"))
#+end_src

** Haskell

The official [[https://github.com/haskell/haskell-mode][Haskell-mode]].

#+begin_src emacs-lisp
(use-package haskell-mode
  :bind (:map haskell-mode-map
         ("C-c C-p" . haskell-process-reload)
         ("C-c C-c" . haskell-process-load-file))
  :config
  (setq haskell-indentation-starter-offset 4)
  (setq haskell-indentation-left-offset 4)
  (setq haskell-indentation-layout-offset 4)
  (setq haskell-indentation-where-pre-offset 4)
  (setq haskell-indentation-where-post-offset 4)
  (setq haskell-interactive-popup-errors nil))
#+end_src

*** Interactive mode

=C-l= clear.

#+begin_src emacs-lisp
(with-eval-after-load 'haskell-interactive-mode
  (bind-key "C-l" 'haskell-interactive-mode-clear 'haskell-interactive-mode-map))
#+end_src

** Python

Python-mode - the one already included in emacs.

*** Indentation

Do not guess anything, Python should be indented with 4 spaces.

#+begin_src emacs-lisp
(setq python-indent-guess-indent-offset nil)
#+end_src

*** Interactive process

Clear the REPL buffer by =C-l=.

#+begin_src emacs-lisp
(bind-key "C-l" 'comint-clear-buffer 'comint-mode-map)
#+end_src

*** Syntax

Flake8 before mypy.

#+begin_src emacs-lisp
(add-hook 'python-mode-hook 'flycheck-mode)

(flycheck-remove-next-checker 'python-flake8 'python-pylint)

(setq flycheck-python-mypy-config "~/.config/mypy/config")
#+end_src

Mypy shall always be strict.

#+begin_src conf :tangle ~/.config/mypy/config
[mypy]
strict = True
#+end_src

*** Typing

Add typing imports automatically.

#+begin_src emacs-lisp
(defun sb/python-update-typing-imports ()
  (interactive)
  (save-excursion
    (goto-char (point-min))
    (when (re-search-forward "^from typing" nil t)
      (move-beginning-of-line 1)
      (kill-line)
      (kill-line))
    (goto-char (point-min))
    (let ((types ""))
      (dolist (type '("Dict" "List" "Optional" "Set" "Tuple"))
        (when (save-excursion
                (search-forward type nil t))
          (setf types (concat types type ", "))))
      (when (not (string= types ""))
        (insert (concat "from typing import "
                        (substring types 0 -2)))
        (newline)))))

(with-eval-after-load 'python
  (bind-key "C-c i" 'sb/python-update-typing-imports 'python-mode-map))
#+end_src

* Snippets

The [[https://github.com/joaotavora/yasnippet][template system]] for Emacs. Global mode doesn't seem to work correctly when in use-package block.

#+begin_src emacs-lisp
(defvar snippet-directory "~/dotfiles/snippets/")

(use-package yasnippet
  :bind* ("C-x n s" . yas-new-snippet)
  :config
  (setq yas-indent-line 'fixed)
  (setq yas-snippet-dirs `(,snippet-directory)))

(yas-global-mode 1)
#+end_src

** Tables

Creating tables of all snippets based on =snippets= directory contents. Separated by major modes.

#+begin_src emacs-lisp
(defun sb/delete-old-snippet-tables ()
  (goto-char (point-min))
  (re-search-forward "^\\*\\* Tables")
  (re-search-forward "^#\\+end_src")
  (set-mark-command nil)
  (re-search-forward "^\\* Window manager")
  (previous-line)
  (delete-region (mark) (point)))

(defun sb/get-snippet-property (file property)
  (let* ((result (concat "grep \"# " property ":\" " file))
         (result (shell-command-to-string result))
         (result (substring result (+ (length property) 4)))
         (result (substring result 0 (- (length result) 1))))
    result))

(defun sb/insert-snippet-table (dir)
  (let ((snippets (cddr (directory-files (expand-file-name dir snippet-directory) t)))
        (dir (replace-regexp-in-string "0" " " (capitalize (replace-regexp-in-string "-" "0" dir)))))
    (org-insert-heading-respect-content)
    (insert dir)
    (dotimes (i 3) (newline))
    (org-table-create "2x1")
    (previous-line)
    (insert "|-")
    (org-table-next-field)
    (insert "Key")
    (org-table-next-field)
    (insert "Name")
    (org-table-insert-hline)
    (next-line)
    (dolist (snippet snippets)
      (org-table-next-field)
      (insert (concat "[[" (replace-regexp-in-string ".*dotfiles/" "file:" snippet)
                      "][" (sb/get-snippet-property snippet "key") "]]"))
      (org-table-next-field)
      (insert (sb/get-snippet-property snippet "name")))
    (org-table-insert-hline)
    (org-table-align)))

(defun sb/insert-snippet-tables ()
  (let ((modes (cddr (directory-files snippet-directory))))
    (save-excursion
      (sb/delete-old-snippet-tables)
      (mapc 'sb/insert-snippet-table modes)
      (when (cdr modes)
        (dotimes (i 2) (next-line))
        (delete-char 1)))))

(add-hook 'toc-org-mode-hook
          (lambda ()
            (add-hook 'before-save-hook
                      'sb/insert-snippet-tables -100 t)))
#+end_src

** Org mode

|-----+--------------------------|
| Key | Name                     |
|-----+--------------------------|
| [[file:snippets/org-mode/co][co]]  | code block configuration |
| [[file:snippets/org-mode/el][el]]  | code block emacs lisp    |
| [[file:snippets/org-mode/hs][hs]]  | code block haskell       |
| [[file:snippets/org-mode/sh][sh]]  | code block shell         |
| [[file:snippets/org-mode/tx][tx]]  | code block text          |
|-----+--------------------------|

* Window manager

[[https://github.com/ch11ng/exwm][Emacs X Window Manager]]. Gets executed if its [[file:X/EXWM.org][configuration file]] exists.

#+begin_src emacs-lisp
(let* ((lisp-dir (concat user-emacs-directory "lisp/"))
       (wm-file (concat lisp-dir "window-manager.el")))
  (when (file-exists-p wm-file)
    (push lisp-dir load-path)
    (require 'window-manager)))
#+end_src
