#+title: "C-c C-v t"
#+property: header-args:emacs-lisp :tangle ~/.emacs.d/init.el

Personal GNU Emacs configuration!

* Essentials

The most general and basic part of the configuration that either prepares background for the other pieces, or simply has no better place to be.

** Package management

Downloading, configuring and using packages.

*** Straight

[[https://github.com/raxod502/straight.el][Straight]] package manager. Making =*straight-process*= invisible.

#+begin_src emacs-lisp
(setq straight-process-buffer " *straight-process*")

(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))
#+end_src

*** Use-package

Integration with [[https://github.com/jwiegley/use-package][use-package]].

#+begin_src emacs-lisp
(straight-use-package 'use-package)
(setq straight-use-package-by-default t)
#+end_src

** No-littering

Using [[https://github.com/emacscollective/no-littering][no-littering]] package to help keeping =~/.emacs.d/= clean.

#+begin_src emacs-lisp
(use-package no-littering
  :custom
  (auto-save-file-name-transforms `((".*" ,(no-littering-expand-var-file-name "auto-save/") t)))
  (custom-file (no-littering-expand-etc-file-name "custom.el")))
#+end_src

* Editing text

Customizing the customizable editor.

** Movement

|---------------------+---------|
| Name                | Binding |
|---------------------+---------|
| scroll-up-command   | C-v     |
| scroll-down-command | M-v     |
| recenter-top-bottom | C-l     |
| forward-char        | C-f     |
| backward-char       | C-b     |
| forward-word        | M-f     |
| backward-word       | M-b     |
| avy-goto-char       | C-j     |
|---------------------+---------|

*** Avy

Jumping to characters with [[https://github.com/abo-abo/avy][avy]].

#+begin_src emacs-lisp
(use-package avy
  :bind* ("C-j" . avy-goto-char))
#+end_src

** Lines

|------------------------+---------|
| Name                   | Binding |
|------------------------+---------|
| move-beginning-of-line | C-a     |
| move-end-of-line       | C-e     |
| next-line              | C-n     |
| previous-line          | C-p     |
| open-line              | C-o     |
| newline                | C-m     |
| kill-line              | C-k     |
|------------------------+---------|

** Mark

|------------------+---------|
| Name             | Binding |
|------------------+---------|
| set-mark-command | C-SPC   |
| kill-region      | C-w     |
| kill-ring-save   | M-w     |
| yank             | C-y     |
| yank-pop         | M-y     |
| expand-region    | C-r     |
|------------------+---------|

*** Expand-region

Expanding region using [[https://github.com/magnars/expand-region.el][expand-region]]. Marked text is replaced by typing.

#+begin_src emacs-lisp
(use-package expand-region
  :bind ("C-r" . er/expand-region)
  :config (setq expand-region-fast-keys-enabled nil))

(delete-selection-mode 1)
#+end_src

** Swapping

|-----------------+---------|
| Name            | Binding |
|-----------------+---------|
| transpose-chars | C-t     |
| transpose-words | M-t     |
| downcase-word   | M-l     |
| upcase-word     | M-u     |
| capitalize-word | M-c     |
|-----------------+---------|
