#+title: GUI.org
#+property: header-args :mkdirp yes
#+property: header-args:text :tangle ./gui_pkglist.txt
#+property: header-args:emacs-lisp :tangle ~/.emacs.d/lisp/window-manager.el

Set up of the graphical user interface. Either window manager EXWM or desktop environment Xfce.

* Xorg

X Window System implemetation [[https://wiki.archlinux.org/title/xorg][Xorg]].

*** Display server

[[https://wiki.archlinux.org/title/Xinit#Autostart_X_at_login][Starting X]] after logging in to bash.

#+begin_src shell :tangle ~/.bash_profile
if [ -z "${DISPLAY}" ] && [ "${XDG_VTNR}" -le 2 ]; then
  exec startx
fi
#+end_src

*** Keyboard layout

US [[https://wiki.archlinux.org/title/Xorg/Keyboard_configuration#Using_setxkbmap][keyboard layout]], czech characters with =AltGr=.

#+begin_src shell :tangle ~/.xinitrc
setxkbmap -layout cz -variant coder
#+end_src

*** Package

Fira Code font. Everything else managed by archinstall.

#+begin_src text
ttf-fira-code
#+end_src

*** TODO Exec

|-----+-------|
| tty | wm/de |
|-----+-------|
|   1 | EXWM  |
|   2 | Xfce  |
| 3-6 | bash  |
|-----+-------|

#+begin_src shell :tangle ~/.xinitrc
if [ "${XDG_VTNR}" -eq 1 ]; then
    xhost +SI:localuser:$USER
    export _JAVA_AWT_WM_NONREPARENTING=1
    xsetroot -cursor_name left_ptr
    xset r rate 200 50
    exec emacs
else
    exec startxfce4
fi
#+end_src

* EXWM

A full-featured [[https://github.com/ch11ng/exwm][tiling X window manager]] for Emacs. Example configuration [[https://github.com/ch11ng/exwm/wiki/Configuration-Example][here]].

#+begin_src emacs-lisp
(use-package exwm
  :config (exwm-enable))
#+end_src

*** Global keys

Executing programs.

#+begin_src emacs-lisp
(defun sb/start-process (command)
  (start-process-shell-command command nil command))

(defun sb/execute-application (command)
  (interactive (list (read-shell-command "$ ")))
  (sb/start-process command))

(defun sb/exwm-add-global-key (cell)
  (let ((key (kbd (car cell)))
        (fun (cdr cell)))
    (when (stringp fun)
      (setq fun
            `(lambda ()
               (interactive)
               (sb/start-process ,fun))))
    `(,key . ,fun)))

(defun sb/exwm-add-global-keys (keys)
  (dolist (key keys)
    (push (sb/exwm-add-global-key key) exwm-input-global-keys)))

(sb/exwm-add-global-keys '(("s-r" . exwm-reset)
                           ("C-x x p" . sb/execute-application)
                           ("C-x x w" . "chromium")
                           ("C-x x v" . "vlc")
                           ;; laptop keys
                           ("<XF86AudioMute>" . "amixer set Master toggle")
                           ("<XF86AudioLowerVolume>" . "amixer set Master 5%-")
                           ("<XF86AudioRaiseVolume>" . "amixer set Master 5%+")
                           ("<XF86AudioMicMute>" . "amixer set Capture nocap")
                           ("<XF86MonBrightnessDown>" . "brightnessctl --min-value=10 s 15%-")
                           ("<XF86MonBrightnessUp>" . "brightnessctl --min-value=10 s 15%+")))
#+end_src

*** Local keys

=C-q= to send raw key to the application.

#+begin_src emacs-lisp
(define-key exwm-mode-map [?\C-q] #'exwm-input-send-next-key)
#+end_src

*** Simulation keys

Mimicking Emacs's behavior.

#+begin_src emacs-lisp
(setq exwm-input-simulation-keys
      '(;; movement
        ([?\C-b] . [left])
        ([?\M-b] . [C-left])
        ([?\C-f] . [right])
        ([?\M-f] . [C-right])
        ([?\C-p] . [up])
        ([?\C-n] . [down])
        ([?\C-a] . [home])
        ([?\C-e] . [end])
        ([?\M-v] . [prior down])
        ([?\C-v] . [next up])
        ([?\C-d] . [delete])
        ([?\C-k] . [S-end delete])
        ;; cut/paste
        ([?\C-w] . [?\C-x])
        ([?\M-w] . [?\C-c])
        ([?\C-y] . [?\C-v])
        ;; search
        ([?\C-s] . [?\C-f])
        ;; keyboard quit
        ([?\C-g] . [])))
#+end_src

*** Hooks

Naming buffers reasonably.

#+begin_src emacs-lisp
(add-hook 'exwm-update-class-hook
          (lambda ()
            (exwm-workspace-rename-buffer exwm-class-name)))
#+end_src

[[https://github.com/daviwil/emacs-from-scratch/blob/master/show-notes/Emacs-Desktop-05.org#starting-polybar-from-emacs][Starting polybar]] from Emacs.

#+begin_src emacs-lisp
(add-hook 'exwm-init-hook
          (lambda ()
            (sb/start-process "polybar poly")))
#+end_src

*** Providing

End of =window-manager.el=.

#+begin_src emacs-lisp
(provide 'window-manager)
#+end_src

* Polybar

A fast and easy-to-use [[https://github.com/polybar/polybar][tool for creating status bars]].

*** Face

Designed to fit in the right part of Emacs' echo area. Color acquired by [[https://aur.archlinux.org/packages/grabc][grabc]].

#+begin_src conf :tangle ~/.config/polybar/config
[bar/poly]
override-redirect = true
bottom = true
fixed-center = false

width = 20%
offset-x = 80%
height = 15

foreground = #ffffff
background = #282a36

font-0 = Fira Code:pixelsize=11:semibold;1

padding = 1
module-margin = 2
modules-right = pulseaudio bluetooth battery date
#+end_src

*** Modules

Volume and bluetooth.

#+begin_src conf :tangle ~/.config/polybar/config
[module/pulseaudio]
type = internal/pulseaudio

label-volume = "%percentage%%  "
label-muted = %percentage%% m

[module/bluetooth]
type = custom/script

exec = sh ~/.config/polybar/bluetooth
#+end_src

Print =b= if bluetooth headphones are connected.

#+begin_src shell :tangle ~/.config/polybar/bluetooth
if [ $(bluetoothctl info | wc -l) -ne 1 ]; then
    echo "b"
else
    echo " "
fi
#+end_src

Time, date and battery.

#+begin_src conf :tangle ~/.config/polybar/config
[module/date]
type = internal/date

date = %d.%m.%Y
time = %H:%M

label = %date% %time%

[module/battery]
type = internal/battery

battery = BAT1
adapter = ACAD
#+end_src

*** Package

#+begin_src text
polybar
#+end_src
