#+title: System.org
#+property: header-args :mkdirp yes
#+property: header-args:text+ :tangle ./pkglist.txt
#+property: header-args:haskell+ :tangle ~/.xmonad/xmonad.hs

Configuration and also a bit of documentation for Arch Linux and the applications that run on it.

* Installation notes

The installation is simplified by [[https://wiki.archlinux.org/title/Archinstall][archinstall]]. That suits me because I hardly need anything else than the defaults.

|------------------------+---------------|
| Question               | Answer        |
|------------------------+---------------|
| bootloader             | systemd-boot  |
| pre-programmed-profile | xorg          |
| additional packages    | git emacs     |
| timezone               | Europe/Prague |
|------------------------+---------------|

* Command-line tools

Used in terminal emulators.

** Systemd

A [[https://wiki.archlinux.org/title/Systemd][suite]] of basic building blocks for a Linux system.

*** Power management

[[https://wiki.archlinux.org/title/Systemd#Power_management][Commands]].

#+begin_src shell
systemctl reboot
systemctl suspend
systemctl poweroff
#+end_src

** Pacman

The [[https://wiki.archlinux.org/title/pacman][package manager]] in Arch Linux.

*** Basic commands

Installing package, removing package with dependencies and full system upgrade respectively.

#+begin_src shell
pacman -S vim
pacman -Rs vim
pacman -Syu
#+end_src

*** Packages from a file

Getting the packages [[https://wiki.archlinux.org/title/Pacman/Tips_and_tricks#Install_packages_from_a_list][from]] tangled file =pkglist.txt= ready.

#+begin_src shell
pacman -S --needed - < dotfiles/pkglist.txt
#+end_src

** Git

Version control system [[https://wiki.archlinux.org/title/git][Git]]. Used mostly by the magit package in Emacs.

#+begin_src conf :tangle ~/.gitconfig
[user]
name = Šimon Brauner
email = simonbrauner@seznam.cz

[core]
editor = emacs

[alias]
graph = log --all --oneline --graph
#+end_src

** OpenSSH

Connecting to other devices with [[https://wiki.archlinux.org/title/OpenSSH][SSH]].

*** Key

[[https://docs.github.com/en/github/authenticating-to-github/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent][New key]].

#+begin_src shell
ssh-keygen -t ed25519 -C "simonbrauner@seznam.cz"
#+end_src

*** Package

#+begin_src text
openssh
#+end_src

** ALSA utilities

[[https://wiki.archlinux.org/title/Advanced_Linux_Sound_Architecture#ALSA_utilities][Sound settings]] with =alsamixer= command.

*** Package

#+begin_src text
alsa-utils
#+end_src

* Window management

Xorg and Xmonad.

** Xorg

X Window System implemetation [[https://wiki.archlinux.org/title/xorg][Xorg]].

*** Display server

[[https://wiki.archlinux.org/title/Xinit#Autostart_X_at_login][Starting X]] after logging in to bash.

#+begin_src shell :tangle ~/.bash_profile
if [ -z "${DISPLAY}" ] && [ "${XDG_VTNR}" -eq 1 ]; then
  exec startx
fi
#+end_src

*** Keyboard layout

US [[https://wiki.archlinux.org/title/Xorg/Keyboard_configuration#Using_setxkbmap][keyboard layout]], czech characters with =AltGr=.

#+begin_src shell :tangle ~/.xinitrc
setxkbmap -layout cz -variant coder
#+end_src

*** Executing Xmonad

Running xmonad with [[https://wiki.archlinux.org/title/xmonad#Starting][xinit]].

#+begin_src shell :tangle ~/.xinitrc
exec xmonad
#+end_src

** Xmonad

A tiling window manager [[https://wiki.archlinux.org/title/xmonad][xmonad]].

*** Imports

#+begin_src haskell
import XMonad
import XMonad.Actions.SpawnOn
import XMonad.Layout.NoBorders
#+end_src

*** Basics

Default programs, super key as leader key.

#+begin_src haskell
myEditor   = "emacs"
myBrowser  = "firefox"
myTerminal = "kitty"

myModMask = mod4Mask
#+end_src

*** Key bindings

|----------------------------+------------|
| Action                     | Binding    |
|----------------------------+------------|
| select workspace 1         | s-1        |
| next window                | s-tab      |
| select window as main      | s-return   |
| move window to workspace 2 | S-s-2      |
| open terminal              | S-s-return |
| close window               | S-s-c      |
|----------------------------+------------|

*** Layout

Borders - colors, size, visible only with multiple windows. =Tall= layout.

#+begin_src haskell
myNormalBorderColor  = "#19194d"
myFocusedBorderColor = "#0033cc"

myBorderWidth = 3

myLayoutHook = smartBorders $ Tall 1 (3/100) (1/2)
#+end_src

*** Workspaces

Nine workspaces, first three of them have applications on startup.

#+begin_src haskell
myWorkspaces = map show [1..9]

myManageHook = manageSpawn <+> manageHook def

myStartupHook = do
  spawnOn "1" myEditor
  spawnOn "2" myBrowser
  spawnOn "3" myTerminal
#+end_src

*** Main

#+begin_src haskell
main = xmonad defaults

defaults = def
  { terminal           = myTerminal
  , modMask            = myModMask
  , normalBorderColor  = myNormalBorderColor
  , focusedBorderColor = myFocusedBorderColor
  , borderWidth        = myBorderWidth
  , layoutHook         = myLayoutHook
  , workspaces         = myWorkspaces
  , manageHook         = myManageHook
  , startupHook        = myStartupHook
  }
#+end_src

*** Pacman hook

Recompiling xmonad [[https://wiki.archlinux.org/title/Xmonad#Problems_with_finding_shared_libraries_after_update][after update]].

#+begin_src conf :tangle /sudo::/etc/pacman.d/hooks/xmonad.hook
[Trigger]
Operation = Upgrade
Type = Package
Target = xmonad

[Action]
Description = Recompiling xmonad...
When = PostTransaction
Exec = /usr/bin/sudo -u sb /usr/bin/xmonad --recompile
#+end_src

*** Packages

#+begin_src text
xmonad
xmonad-contrib
#+end_src

** Dmenu

[[https://wiki.archlinux.org/title/dmenu][Dynamic menu]]. Used to open programs. Bound to =s-p=.

*** Package

#+begin_src text
dmenu
#+end_src

* GUI programs

Displayed by the X Window System.

** Emacs

The extensible, customizable, self-documenting, real-time display editor. Configured in its own file.

*** Packages

Vterm dependencies and Fira Code font.

#+begin_src text
cmake
libtool
libvterm
ttf-fira-code
#+end_src

** Firefox

A web browser.

*** Package

#+begin_src text
firefox
#+end_src

** Kitty

Terminal emulator [[https://github.com/kovidgoyal/kitty][Kitty]], setting the font size.

#+begin_src conf :tangle ~/.config/kitty/kitty.conf
font_size 20.0
#+end_src

*** Package

#+begin_src text
kitty
#+end_src

** Feh

A light-weight, configurable and versatile image viewer - [[https://github.com/derf/feh][Feh]].

*** Package

#+begin_src text
feh
#+end_src
