#+title: System configuration
#+property: header-args :mkdirp yes
#+property: header-args:text+ :tangle ./pkglist.txt
#+property: header-args:haskell+ :tangle ~/.xmonad/xmonad.hs

Configuration of the Arch Linux GNU/Linux distribution.

* Command-line tools

Used in terminal emulators.

** Git

Acquired manualy after system installation.

#+begin_src conf :tangle ~/.gitconfig
[user]
name = Šimon Brauner
email = simonbrauner@seznam.cz

[core]
editor = emacs

[alias]
graph = log --all --oneline --graph
#+end_src

** ALSA utilities

[[https://wiki.archlinux.org/title/Advanced_Linux_Sound_Architecture#ALSA_utilities][Sound settings]] with =alsamixer= command.

*** Package

#+begin_src text
alsa-utils
#+end_src

* Window management

Xorg and Xmonad.

** Xorg

X Window System implemetation [[https://wiki.archlinux.org/title/xorg][Xorg]]. Prepared by [[https://wiki.archlinux.org/title/Archinstall][archinstall]].

*** Display server

[[https://wiki.archlinux.org/title/Xinit#Autostart_X_at_login][Starting X]] after logging in to bash.

#+begin_src shell :tangle ~/.bash_profile
if [ -z "${DISPLAY}" ] && [ "${XDG_VTNR}" -eq 1 ]; then
  exec startx
fi
#+end_src

*** Keyboard layout

US [[https://wiki.archlinux.org/title/Xorg/Keyboard_configuration#Using_setxkbmap][keyboard layout]], czech characters with =AltGr=.

#+begin_src shell :tangle ~/.xinitrc
setxkbmap -layout cz -variant coder
#+end_src

*** Executing Xmonad

Running xmonad with [[https://wiki.archlinux.org/title/xmonad#Starting][xinit]].

#+begin_src shell :tangle ~/.xinitrc
exec xmonad
#+end_src

** Xmonad

A tiling window manager [[https://wiki.archlinux.org/title/xmonad][xmonad]].

*** Imports

#+begin_src haskell
import XMonad
import XMonad.Actions.SpawnOn
import XMonad.Layout.NoBorders
#+end_src

*** Basics

Default programs, super key as leader key.

#+begin_src haskell
myEditor   = "emacs"
myBrowser  = "firefox"
myTerminal = "kitty"

myModMask = mod4Mask
#+end_src

*** Key bindings

|----------------------------+------------|
| Action                     | Binding    |
|----------------------------+------------|
| select workspace 1         | s-1        |
| next window                | s-tab      |
| select window as main      | s-return   |
| move window to workspace 2 | S-s-2      |
| open terminal              | S-s-return |
| close window               | S-s-c      |
|----------------------------+------------|

*** Layout

Borders - colors, size, visible only with multiple windows. =Tall= layout.

#+begin_src haskell
myNormalBorderColor  = "#19194d"
myFocusedBorderColor = "#0033cc"

myBorderWidth = 3

myLayoutHook = smartBorders $ Tall 1 (3/100) (1/2)
#+end_src

*** Workspaces

Nine workspaces, first three of them have applications on startup.

#+begin_src haskell
myWorkspaces = map show [1..9]

myManageHook = manageSpawn <+> manageHook def

myStartupHook = do
  spawnOn "1" myEditor
  spawnOn "2" myBrowser
  spawnOn "3" myTerminal
#+end_src

*** Main

#+begin_src haskell
main = xmonad defaults

defaults = def
  { terminal           = myTerminal
  , modMask            = myModMask
  , normalBorderColor  = myNormalBorderColor
  , focusedBorderColor = myFocusedBorderColor
  , borderWidth        = myBorderWidth
  , layoutHook         = myLayoutHook
  , workspaces         = myWorkspaces
  , manageHook         = myManageHook
  , startupHook        = myStartupHook
  }
#+end_src

*** Pacman hook

Recompiling xmonad [[https://wiki.archlinux.org/title/Xmonad#Problems_with_finding_shared_libraries_after_update][after update]].

#+begin_src conf :tangle /sudo::/etc/pacman.d/hooks/xmonad.hook
[Trigger]
Operation = Upgrade
Type = Package
Target = xmonad

[Action]
Description = Recompiling xmonad...
When = PostTransaction
Exec = /usr/bin/sudo -u sb /usr/bin/xmonad --recompile
#+end_src

*** Packages

#+begin_src text
xmonad
xmonad-contrib
#+end_src

** Dmenu

[[https://wiki.archlinux.org/title/dmenu][Dynamic menu]]. Used to open programs. Bound to =s-p=.

*** Package

#+begin_src text
dmenu
#+end_src

* GUI programs

Displayed by the X Window System.

** Emacs

The extensible, customizable, self-documenting, real-time display editor. Configured in it's own file.

*** Packages

Including vterm dependencies and a font.

#+begin_src text
emacs
cmake
libtool
libvterm
ttf-fira-code
#+end_src

** Firefox

A web browser.

*** Package

#+begin_src text
firefox
#+end_src

** Kitty

Terminal emulator [[https://github.com/kovidgoyal/kitty][Kitty]], setting the font size.

#+begin_src conf :tangle ~/.config/kitty/kitty.conf
font_size 20.0
#+end_src

*** Package

#+begin_src text
kitty
#+end_src

** Feh

A light-weight, configurable and versatile image viewer - [[https://github.com/derf/feh][Feh]].

*** Package

#+begin_src text
feh
#+end_src
