#+title: System.org
#+property: header-args :mkdirp yes
#+property: header-args:text :tangle ./pkglist.txt
#+property: header-args:haskell :tangle ~/.xmonad/xmonad.hs

* Command-line tools

Used in terminal emulators.

** BlueZ

[[https://wiki.archlinux.org/title/bluetooth][Bluetooth]] implementation. Connects automatically to bluetooth headphones.

*** Autostart

Auto power-on [[https://wiki.archlinux.org/title/bluetooth#Auto_power-on_after_boot][after boot]].

#+begin_src conf :tangle /sudo::/etc/bluetooth/main.conf
[Policy]
AutoEnable=true
#+end_src

*** Packages

#+begin_src text
bluez
bluez-utils
#+end_src

** Sound

Using [[https://wiki.archlinux.org/title/Advanced_Linux_Sound_Architecture][ALSA utilities]] and [[https://wiki.archlinux.org/title/PulseAudio][PulseAudio]] to manage sound.

*** Stop error message

Avoiding [[https://forums.lenovo.com/t5/Other-Linux-Discussions/AMD-T14-kernel-error-about-acp-pdm-mach/m-p/5066593?page=1#5339535][this]] message shown at the login screen by adding the [[https://wiki.archlinux.org/title/kernel_parameters#systemd-boot][kernel parameter]]. Not tangled because tramp finds it difficult.

#+begin_src conf
snd_rn_pci_acp3x.dmic_acpi_check=0
#+end_src

*** Packages

#+begin_src text
alsa-utils
pulseaudio
pulseaudio-alsa
pulseaudio-bluetooth
#+end_src

** Backlight

Changing the [[https://wiki.archlinux.org/title/backlight#Backlight_utilities][screen brightness]] with =brightnessctl=.

*** Package

#+begin_src text
brightnessctl
#+end_src

** Neofetch

System information and logo by [[https://github.com/dylanaraps/neofetch][neofetch]].

*** Before login

Configured to show constant info only. =Memory= and =Disk= hardcoded to avoid irrelevant ratios. =Terminal= is the only dynamic part - it shows the tty number.

#+begin_src conf :tangle ~/.config/neofetch/config.conf
print_info() {
    info model
    info underline
    info "CPU" cpu
    info "GPU" gpu
    info "Resolution" resolution
    info "Memory" memory
    info "Disk" disk

    prin
    prin
    prin
    info distro
    info underline
    info "Shell" shell
    info "GPU Driver" gpu_driver
    info "WM" wm
    info "Terminal" term
}

get_memory() {
    memory="7295MiB"
}

get_disk() {
    disk="234G"
}

get_term() {
    term="\l"
}

shell_version="off"
speed_shorthand="on"
disk_subtitle="none"
#+end_src

*** Issue file

Showing neofetch at the bash login screen by saving the output into =/etc/issue= file.

#+begin_src shell
neofetch --config /home/sb/.config/neofetch/config.conf > /etc/issue
#+end_src

*** Package

#+begin_src text
neofetch
#+end_src

* GUI programs

Displayed by the X Window System.

** Emacs

The extensible, customizable, self-documenting, real-time display editor. Configured in its own file.

** Firefox

A web browser.

*** Package

#+begin_src text
firefox
#+end_src

** Kitty

Terminal emulator [[https://github.com/kovidgoyal/kitty][Kitty]], setting the font size.

#+begin_src conf :tangle ~/.config/kitty/kitty.conf
font_family Fira Code
font_size 14.0
#+end_src

*** Package

#+begin_src text
kitty
#+end_src

** Feh

A light-weight, configurable and versatile image viewer - [[https://github.com/derf/feh][Feh]].

*** Package

#+begin_src text
feh
#+end_src

** VLC

Video player [[https://wiki.archlinux.org/title/VLC_media_player][VLC]].

*** Package

#+begin_src text
vlc
#+end_src

** NM-applet

NetworkManager [[https://wiki.archlinux.org/title/NetworkManager#nm-applet][front-end]] to connect to [[https://it.muni.cz/sluzby/wifi/navody/desktopove-operacni-systemy/eduroam-na-linux-ubuntu][eduroam]].

#+begin_src shell
#!/bin/sh
nm-applet    2>&1 > /dev/null &
stalonetray  2>&1 > /dev/null
killall nm-applet
#+end_src

*** Packages

#+begin_src text
network-manager-applet
stalonetray
#+end_src

* Programming languages

Compilers, interpreters,...

** Haskell

[[https://wiki.archlinux.org/title/haskell#Installation][Glasgow Haskell Compiler]].

*** Package

#+begin_src text
ghc
#+end_src

** Python

[[https://github.com/python/cpython][CPython]] with pip and tk.

*** Packages

#+begin_src text
python
python-pip
tk
#+end_src
