#+title: System.org
#+property: header-args :mkdirp yes
#+property: header-args:text :tangle ./packages/system_pkglist.txt

Configuration of the Arch Linux operating system.

* Installation

The installation is simplified by [[https://wiki.archlinux.org/title/Archinstall][archinstall]]. That suits me because I hardly need anything else than the defaults. Log is located in =/var/log/archinstall/install.log=.

|----------|
| packages |
|----------|
| emacs    |
| git      |
|----------|

* Documentation

The [[https://wiki.archlinux.org/title/man_page][manual pages]].

*** Packages

#+begin_src text
man-db
man-pages
#+end_src

* Polkit

[[https://wiki.archlinux.org/title/allow_users_to_shutdown#Using_systemd-logind][Allow users]] to do power related tasks.

*** Package

#+begin_src text
polkit
#+end_src

* Htop

Keeping an eye on processes with [[https://github.com/htop-dev/htop][htop]].

*** Package

#+begin_src text
htop
#+end_src

* Ncdu

[[https://dev.yorhel.nl/ncdu][Ncdu]] to monitor disk usage.

*** Package

#+begin_src text
ncdu
#+end_src

* Zip and unzip

Programs to work with =.zip= archives.

*** Packages

#+begin_src text
zip
unzip
#+end_src

* Sound

Using [[https://wiki.archlinux.org/title/Advanced_Linux_Sound_Architecture][ALSA utilities]] and [[https://wiki.archlinux.org/title/PulseAudio][PulseAudio]] to manage sound.

*** Packages

#+begin_src text
alsa-utils
pulseaudio
pulseaudio-alsa
pulseaudio-bluetooth
#+end_src

* Bluetooth

[[https://wiki.archlinux.org/title/bluetooth][BlueZ]] implementation. Systemd service =bluetooth= must be enabled. Pairing described [[https://wiki.archlinux.org/title/bluetooth#Pairing][there]].

*** Autostart

Auto power-on [[https://wiki.archlinux.org/title/bluetooth#Auto_power-on_after_boot/resume][after boot]].

#+begin_src conf :tangle /sudo::/etc/bluetooth/main.conf
[Policy]
AutoEnable=true
#+end_src

*** Pavucontrol

Headphones need need to be [[https://bbs.archlinux.org/viewtopic.php?id=215268][selected]] as default.

*** Packages

#+begin_src text
bluez
bluez-utils
pavucontrol
#+end_src

* Backlight

Changing the screen brightness.

*** Package

#+begin_src text
brightnessctl
#+end_src
