#+title: Xmonad.org
#+property: header-args :mkdirp yes

Xmonad and Xmobar.

* Xmonad

A tiling window manager [[https://wiki.archlinux.org/title/xmonad][xmonad]].

** Imports

#+begin_src haskell :tangle ~/.xmonad/xmonad.hs
import XMonad
import XMonad.Util.EZConfig
import XMonad.Actions.SpawnOn
import XMonad.Layout.NoBorders
import XMonad.Hooks.DynamicLog
#+end_src

** Basics

Default programs, super key as leader key.

#+begin_src haskell :tangle ~/.xmonad/xmonad.hs
myEditor   = "emacs"
myBrowser  = "firefox"
myTerminal = "kitty"

myModMask = mod4Mask
#+end_src

** Key bindings

The basic default keybindings.

|----------------------------+------------|
| Action                     | Binding    |
|----------------------------+------------|
| select workspace 1         | s-1        |
| next window                | s-tab      |
| select window as main      | s-return   |
| move window to workspace 2 | S-s-2      |
| open terminal              | S-s-return |
| close window               | S-s-c      |
| toggle xmobar              | s-b        |
|----------------------------+------------|

And some additional self-explanatory laptop-specific ones.

#+begin_src haskell :tangle ~/.xmonad/xmonad.hs
myKeys =
    [ ("<XF86AudioMute>",         spawn "amixer set Master toggle")
    , ("<XF86AudioLowerVolume>",  spawn "amixer set Master 5%-")
    , ("<XF86AudioRaiseVolume>",  spawn "amixer set Master 5%+")
    , ("<XF86AudioMicMute>",      spawn "amixer set Capture toggle")
    , ("<XF86MonBrightnessDown>", spawn "brightnessctl s 20%-")
    , ("<XF86MonBrightnessUp>",   spawn "brightnessctl s 20%+")
    ]
#+end_src

** Layout

Borders - colors, size, visible only with multiple windows. =Tall= layout.

#+begin_src haskell :tangle ~/.xmonad/xmonad.hs
myNormalBorderColor  = "#19194d"
myFocusedBorderColor = "#0033cc"

myBorderWidth = 3

myLayoutHook = smartBorders $ Tall 1 (3/100) (1/2)
#+end_src

** Workspaces

Nine workspaces, first three of them have applications on startup.

#+begin_src haskell :tangle ~/.xmonad/xmonad.hs
myWorkspaces = map show [1..9]

myManageHook = manageSpawn <+> manageHook def

myStartupHook = do
    spawnOn "1" myEditor
    spawnOn "2" myBrowser
    spawnOn "3" myTerminal
#+end_src

** Main

#+begin_src haskell :tangle ~/.xmonad/xmonad.hs
main = xmonad =<< xmobar defaults

defaults = def
    { terminal           = myTerminal
    , modMask            = myModMask
    , normalBorderColor  = myNormalBorderColor
    , focusedBorderColor = myFocusedBorderColor
    , borderWidth        = myBorderWidth
    , layoutHook         = myLayoutHook
    , workspaces         = myWorkspaces
    , manageHook         = myManageHook
    , startupHook        = myStartupHook
    } `additionalKeysP` myKeys
#+end_src

** Pacman hook

Recompiling xmonad [[https://wiki.archlinux.org/title/Xmonad#Problems_with_finding_shared_libraries_after_update][after update]].

#+begin_src conf :tangle /sudo::/etc/pacman.d/hooks/xmonad.hook
[Trigger]
Operation = Upgrade
Type = Package
Target = xmonad

[Action]
Description = Recompiling xmonad...
When = PostTransaction
Exec = /usr/bin/sudo -u sb /usr/bin/xmonad --recompile
#+end_src

** Packages

#+begin_src text
xmonad
xmonad-contrib
#+end_src

* Xmobar

Status bar called [[https://wiki.archlinux.org/title/Xmobar][xmobar]].

** Main

Border color designed to match emacs' screen separator. Special signs: =%%= for plugins, =}{= to separate left and right sides.

#+begin_src haskell :tangle ~/.xmobarrc
Config
    { font        = "xft:Fira Code:size=8"
    , additionalFonts = [ "xft:Fira Code:size=8:bold" ]
    , bgColor     = "black"
    , fgColor     = "white"
    , position    = Top
    , border      = BottomB
    , borderColor = "#373844"

    , template = "  %battery%  |  %multicpu%  |  %memory%}{\
                 \%default:Master%  |  %default:Capture%  |  %bright%  |  %date%  "
    , commands =
#+end_src

** Plugins

Documentation [[https://github.com/jaor/xmobar/blob/master/doc/plugins.org][there]]. Refresh rate in =seconds/10=. =Volume= instead of =Alsa= to be able to see volume of bluetooth device.

#+begin_src haskell :tangle ~/.xmobarrc
[ Run Battery    [ "-t" , "Battery: <fn=1><left>%</fn>"
                 , "-L" , "20"
                 , "-H" , "60"
                 , "-l" , "red"
                 , "-n" , "orange"
                 , "-h" , "green"
                 ] 50
, Run MultiCpu   [ "-t" , "Cpu: <fn=1><total>%</fn>"
                 , "-L" , "10"
                 , "-H" , "50"
                 , "-l" , "green"
                 , "-n" , "orange"
                 , "-h" , "red"
                 ] 20
, Run Memory     [ "-t" , "Memory: <fn=1><usedratio>%</fn>"
                 , "-L" , "20"
                 , "-H" , "40"
                 , "-l" , "green"
                 , "-n" , "orange"
                 , "-h" , "red"
                 ] 20
, Run Volume     "default" "Master"
                 [ "-t" , "Volume: <fn=1><volume>% <status></fn>"] 10
, Run Volume     "default" "Capture"
                 [ "-t" , "Microphone: <fn=1><volume>% <status></fn>"] 10
, Run Brightness [ "-t" , "Brightness: <fn=1><percent>%</fn>"
                 , "--"
                 , "-D" , "/sys/class/backlight/amdgpu_bl0"
                 ] 10
, Run Date       "<fn=1>%a %d.%m.%Y %R</fn>" "date" 10
]}
#+end_src

** Packages

#+begin_src text
xmobar
#+end_src
